// Vendors Manrope + Caveat from Google Fonts into this directory as local
// woff2 files plus a self-contained fonts.css.
//
// Why local rather than the CDN @import that entry.css originally used:
// headless Chromium in the render check cannot reach fonts.gstatic.com, so
// every one of the ~330 preview pages stalled waiting on the stylesheet —
// the first validate run managed 48 screenshots before it was killed. Local
// files also mean a design rendered from this bundle never depends on a
// third-party host being reachable.
//
// Only the `latin` subset is kept: _app.tsx loads both families with
// `subsets: ["latin"]`, so the other subsets are dead weight.
//
// Re-run with:  node .design-sync/fonts/fetch-fonts.mjs
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
// A modern browser UA is required — Google serves ttf to unknown clients.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36';
const SRC =
  'https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&family=Caveat:wght@400..700&display=swap';

const css = await fetch(SRC, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`google fonts css: HTTP ${r.status}`);
  return r.text();
});

// Google emits `/* <subset> */` immediately before each @font-face block.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
  .map(([, subset, rule]) => ({ subset, rule }))
  .filter((b) => b.subset === 'latin');

if (!blocks.length) throw new Error('no latin @font-face blocks found — did the CSS format change?');

const out = [];
for (const { rule } of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(rule)?.[1] ?? 'font';
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(rule)?.[1];
  if (!url) continue;

  const file = `${family.toLowerCase()}-latin.woff2`;
  const bytes = Buffer.from(
    await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
      if (!r.ok) throw new Error(`${url}: HTTP ${r.status}`);
      return r.arrayBuffer();
    }),
  );
  writeFileSync(join(HERE, file), bytes);
  console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} KB`);

  out.push(rule.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('./${file}')`));
}

writeFileSync(
  join(HERE, 'fonts.css'),
  `/* Generated by fetch-fonts.mjs — do not hand-edit.\n` +
    ` * Manrope + Caveat, latin subset, vendored from Google Fonts so the\n` +
    ` * bundle carries its own faces instead of depending on a CDN. */\n\n` +
    out.join('\n\n') +
    '\n',
);
console.log(`fonts.css  ${out.length} @font-face rule(s)`);
