CREATE TABLE public.vehicle_catalog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make text NOT NULL,
    model text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(make, model)
);

-- Enable RLS (Public Read-Only)
ALTER TABLE public.vehicle_catalog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.vehicle_catalog
    FOR SELECT USING (true);

-- Indexes for performance
CREATE INDEX idx_vehicle_catalog_make ON public.vehicle_catalog(make);