CREATE TABLE IF NOT EXISTS public.debug_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_message JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Temporarily disable RLS for debugging. We will secure or remove this table later.
ALTER TABLE public.debug_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access for debugging" ON public.debug_logs;
CREATE POLICY "Allow all access for debugging" ON public.debug_logs FOR ALL USING (true) WITH CHECK (true);