-- Extend the vehicle catalog (makes/models) with models missing for the
-- Swiss/European market, model years 2010 onwards.
-- Mirrors public/Makes_Models_V2.csv; idempotent (on conflict do nothing).

insert into public.makes (name, normalized_name)
select v.name, public.normalize_vehicle_name(v.name)
from (values
  ('Abarth'),
  ('Aiways'),
  ('Alpina'),
  ('BYD'),
  ('Caterham'),
  ('Chrysler'),
  ('Dodge'),
  ('Fisker'),
  ('Jaecoo'),
  ('KTM'),
  ('MG'),
  ('Maxus'),
  ('Omoda'),
  ('RAM'),
  ('Saab')
) as v(name)
on conflict (normalized_name) do nothing;

create temporary table tmp_catalog_additions (make text not null, model text not null);

insert into tmp_catalog_additions (make, model) values
  ('Abarth', '124 Spider'),
  ('Abarth', '500'),
  ('Abarth', '500e'),
  ('Abarth', '595'),
  ('Abarth', '600e'),
  ('Abarth', '695'),
  ('Aiways', 'U5'),
  ('Aiways', 'U6'),
  ('Alfa Romeo', '159'),
  ('Alfa Romeo', 'Brera'),
  ('Alfa Romeo', 'Spider'),
  ('Alpina', 'B3'),
  ('Alpina', 'B4'),
  ('Alpina', 'B5'),
  ('Alpina', 'B6'),
  ('Alpina', 'B7'),
  ('Alpina', 'B8'),
  ('Alpina', 'D3'),
  ('Alpina', 'D4'),
  ('Alpina', 'D5'),
  ('Alpina', 'XB7'),
  ('Alpina', 'XD3'),
  ('Alpina', 'XD4'),
  ('Alpine', 'A390'),
  ('Aston Martin', 'Cygnet'),
  ('Aston Martin', 'DBS'),
  ('Aston Martin', 'One-77'),
  ('Aston Martin', 'Valour'),
  ('Aston Martin', 'Virage'),
  ('Aston Martin', 'Vulcan'),
  ('Audi', 'A3 Cabriolet'),
  ('Audi', 'A4 Avant'),
  ('Audi', 'A4 allroad'),
  ('Audi', 'A5 Cabriolet'),
  ('Audi', 'A5 Sportback'),
  ('Audi', 'A6 Avant'),
  ('Audi', 'A6 allroad'),
  ('Audi', 'RS e-tron GT'),
  ('BMW', '114d'),
  ('BMW', '114i'),
  ('BMW', '123d'),
  ('BMW', '128ti'),
  ('BMW', '135i'),
  ('BMW', '216d'),
  ('BMW', '216i'),
  ('BMW', '316d'),
  ('BMW', '325i'),
  ('BMW', '328i'),
  ('BMW', '428i'),
  ('BMW', '525d'),
  ('BMW', '528i'),
  ('BMW', '535i'),
  ('BMW', 'M550i'),
  ('BMW', 'XM'),
  ('BYD', 'Atto 2'),
  ('BYD', 'Atto 3'),
  ('BYD', 'Dolphin'),
  ('BYD', 'Dolphin Surf'),
  ('BYD', 'Han'),
  ('BYD', 'Seal'),
  ('BYD', 'Seal 6 DM-i'),
  ('BYD', 'Seal U'),
  ('BYD', 'Sealion 7'),
  ('BYD', 'Tang'),
  ('Bugatti', 'Tourbillon'),
  ('Cadillac', 'Escalade'),
  ('Cadillac', 'SRX'),
  ('Caterham', 'Seven'),
  ('Chevrolet', 'Aveo'),
  ('Chevrolet', 'Camaro'),
  ('Chevrolet', 'Captiva'),
  ('Chevrolet', 'Corvette'),
  ('Chevrolet', 'Cruze'),
  ('Chevrolet', 'Volt'),
  ('Chrysler', '300C'),
  ('Chrysler', 'Grand Voyager'),
  ('Citroën', 'C-Crosser'),
  ('Citroën', 'C-Elysée'),
  ('Citroën', 'C-Zero'),
  ('Citroën', 'C1'),
  ('Citroën', 'C4 Aircross'),
  ('Citroën', 'C4 Cactus'),
  ('Citroën', 'C5'),
  ('Citroën', 'C6'),
  ('Citroën', 'C8'),
  ('Citroën', 'DS4'),
  ('Citroën', 'DS5'),
  ('Citroën', 'Nemo'),
  ('Cupra', 'Raval'),
  ('DS', '7'),
  ('Daihatsu', 'Charade'),
  ('Daihatsu', 'Copen'),
  ('Daihatsu', 'Materia'),
  ('Daihatsu', 'Sirion'),
  ('Daihatsu', 'Terios'),
  ('Daihatsu', 'Trevis'),
  ('Dodge', 'Avenger'),
  ('Dodge', 'Caliber'),
  ('Dodge', 'Journey'),
  ('Dodge', 'Nitro'),
  ('Ferrari', '599'),
  ('Ferrari', '612 Scaglietti'),
  ('Ferrari', '849 Testarossa'),
  ('Ferrari', 'Amalfi'),
  ('Ferrari', 'California'),
  ('Fiat', 'Bravo'),
  ('Fiat', 'Croma'),
  ('Fiat', 'Ducato'),
  ('Fiat', 'Idea'),
  ('Fiat', 'Sedici'),
  ('Fisker', 'Karma'),
  ('Fisker', 'Ocean'),
  ('Ford', 'Bronco'),
  ('Ford', 'Fusion'),
  ('Ford', 'Grand C-MAX'),
  ('Honda', 'Civic Type R'),
  ('Honda', 'Prelude'),
  ('Hyundai', 'Elantra'),
  ('Hyundai', 'Grand Santa Fe'),
  ('Infiniti', 'EX'),
  ('Infiniti', 'FX'),
  ('Infiniti', 'M'),
  ('Jaecoo', '5'),
  ('Jaecoo', '7'),
  ('Jaguar', 'XK'),
  ('Jeep', 'Gladiator'),
  ('KTM', 'X-Bow'),
  ('Kia', 'EV2'),
  ('Kia', 'Optima'),
  ('Kia', 'ProCeed'),
  ('Kia', 'Rio'),
  ('Kia', 'Venga'),
  ('Koenigsegg', 'One:1'),
  ('Lada', 'Granta'),
  ('Lada', 'Niva'),
  ('Lamborghini', 'Fenomeno'),
  ('Lamborghini', 'Gallardo'),
  ('Lamborghini', 'Murciélago'),
  ('Lancia', 'Delta'),
  ('Lancia', 'Flavia'),
  ('Lancia', 'Musa'),
  ('Lancia', 'Thema'),
  ('Land Rover', 'Freelander'),
  ('Leapmotor', 'B10'),
  ('Lexus', 'GS'),
  ('Lexus', 'IS'),
  ('Lexus', 'LFA'),
  ('MG', 'Cyberster'),
  ('MG', 'HS'),
  ('MG', 'MG3'),
  ('MG', 'MG4'),
  ('MG', 'MG5'),
  ('MG', 'Marvel R'),
  ('MG', 'S5 EV'),
  ('MG', 'ZS'),
  ('Maserati', 'MCPura'),
  ('Maxus', 'Mifa 9'),
  ('Maxus', 'T90 EV'),
  ('Maxus', 'eDeliver 3'),
  ('Maxus', 'eDeliver 9'),
  ('Mazda', '6e'),
  ('Mazda', 'CX-7'),
  ('Mazda', 'RX-8'),
  ('McLaren', '12C'),
  ('McLaren', '540C'),
  ('McLaren', '570GT'),
  ('McLaren', '570S'),
  ('McLaren', '600LT'),
  ('McLaren', '620R'),
  ('McLaren', '650S'),
  ('McLaren', '675LT'),
  ('McLaren', '720S'),
  ('McLaren', '750S'),
  ('McLaren', '765LT'),
  ('McLaren', 'GTS'),
  ('McLaren', 'W1'),
  ('Mercedes', 'E 250'),
  ('Mercedes', 'E 450'),
  ('Mercedes', 'E 500'),
  ('Mercedes', 'G 580'),
  ('Mercedes', 'GL'),
  ('Mercedes', 'GLK'),
  ('Mercedes', 'ML'),
  ('Mercedes', 'Marco Polo'),
  ('Mercedes', 'Maybach GLS 600'),
  ('Mercedes', 'R-Klasse'),
  ('Mercedes', 'SLS AMG'),
  ('Mercedes', 'Viano'),
  ('Mercedes', 'Vito'),
  ('Mitsubishi', 'Grandis'),
  ('Nissan', 'Interstar'),
  ('Nissan', 'NV200'),
  ('Nissan', 'Note'),
  ('Nissan', 'Pixo'),
  ('Nissan', 'Primastar'),
  ('Nissan', 'Pulsar'),
  ('Nissan', 'Qashqai+2'),
  ('Nissan', 'e-NV200'),
  ('Omoda', '5'),
  ('Omoda', '9'),
  ('Omoda', 'E5'),
  ('Opel', 'Astra H'),
  ('Opel', 'Combo C'),
  ('Opel', 'Corsa D'),
  ('Opel', 'Vivaro A'),
  ('Opel', 'Zafira B'),
  ('Opel', 'Zafira Life'),
  ('Pagani', 'Huayra'),
  ('Pagani', 'Zonda'),
  ('Peugeot', '107'),
  ('Peugeot', '207'),
  ('Peugeot', '301'),
  ('Peugeot', '308 CC'),
  ('Peugeot', '4007'),
  ('Peugeot', '407'),
  ('Peugeot', '607'),
  ('Peugeot', '807'),
  ('Peugeot', 'E-2008'),
  ('Porsche', '911 GT2 RS'),
  ('Porsche', '911 Targa'),
  ('Porsche', 'Cayenne Coupé'),
  ('Porsche', 'Panamera Sport Turismo'),
  ('Porsche', 'Taycan Cross Turismo'),
  ('RAM', '1500'),
  ('Renault', 'Fluence'),
  ('Renault', 'Modus'),
  ('Renault', 'Wind'),
  ('Saab', '9-3'),
  ('Saab', '9-5'),
  ('Seat', 'Exeo'),
  ('SsangYong', 'Rodius'),
  ('Subaru', 'Tribeca'),
  ('Suzuki', 'Alto'),
  ('Suzuki', 'Kizashi'),
  ('Suzuki', 'Splash'),
  ('Suzuki', 'e Vitara'),
  ('Toyota', 'Prius Plus'),
  ('Vauxhall', 'Astra H'),
  ('Vauxhall', 'Combo C'),
  ('Vauxhall', 'Corsa D'),
  ('Vauxhall', 'Vivaro A'),
  ('Vauxhall', 'Vivaro Life'),
  ('Vauxhall', 'Zafira B'),
  ('Volkswagen', 'Fox'),
  ('Volkswagen', 'Golf Alltrack'),
  ('Volkswagen', 'Golf Cabriolet'),
  ('Volkswagen', 'Golf Plus'),
  ('Volkswagen', 'Golf Sportsvan'),
  ('Volkswagen', 'ID. Polo'),
  ('Volkswagen', 'Passat Alltrack'),
  ('Volkswagen', 'Passat Variant'),
  ('Volkswagen', 'Tiguan Allspace'),
  ('Volkswagen', 'e-Golf'),
  ('Volkswagen', 'e-up!'),
  ('Volvo', 'C30'),
  ('Volvo', 'C70'),
  ('Volvo', 'EX60'),
  ('Volvo', 'S40'),
  ('Volvo', 'V40 Cross Country'),
  ('Volvo', 'V50'),
  ('Volvo', 'V60 Cross Country'),
  ('Volvo', 'V90 Cross Country'),
  ('Škoda', 'Enyaq Coupé'),
  ('Škoda', 'Epiq');

insert into public.models (make_id, name, normalized_name, source)
select mk.id, a.model, public.normalize_vehicle_name(a.model), 'catalog_extension_2010_onwards'
from tmp_catalog_additions a
join public.makes mk
  on mk.normalized_name = public.normalize_vehicle_name(a.make)
on conflict (make_id, normalized_name) do nothing;

drop table tmp_catalog_additions;
