-- Extend the vehicle catalog (makes/models) with models missing for the
-- Swiss/European market, model years 2010 onwards.
-- Mirrors public/Makes_Models_V2.csv; idempotent (on conflict do nothing).

insert into public.makes (name, normalized_name)
select v.name, public.normalize_vehicle_name(v.name)
from (values
  ('Abarth'),
  ('Aiways'),
  ('Alpina'),
  ('BYD'),
  ('Caterham'),
  ('Chrysler'),
  ('Dodge'),
  ('Fisker'),
  ('Jaecoo'),
  ('KTM'),
  ('MG'),
  ('Maxus'),
  ('Omoda'),
  ('RAM'),
  ('Saab')
) as v(name)
on conflict (normalized_name) do nothing;

create temporary table tmp_catalog_additions (make text not null, model text not null);

insert into tmp_catalog_additions (make, model) values
  ('Abarth', '124 Spider'),
  ('Abarth', '500'),
  ('Abarth', '500e'),
  ('Abarth', '595'),
  ('Abarth', '600e'),
  ('Abarth', '695'),
  ('Abarth', 'Punto Evo'),
  ('Aiways', 'U5'),
  ('Aiways', 'U6'),
  ('Alfa Romeo', '147'),
  ('Alfa Romeo', '159'),
  ('Alfa Romeo', '8C Spider'),
  ('Alfa Romeo', 'Brera'),
  ('Alfa Romeo', 'GT'),
  ('Alfa Romeo', 'Spider'),
  ('Alpina', 'B3'),
  ('Alpina', 'B4'),
  ('Alpina', 'B5'),
  ('Alpina', 'B6'),
  ('Alpina', 'B7'),
  ('Alpina', 'B8'),
  ('Alpina', 'D3'),
  ('Alpina', 'D4'),
  ('Alpina', 'D5'),
  ('Alpina', 'XB7'),
  ('Alpina', 'XD3'),
  ('Alpina', 'XD4'),
  ('Alpine', 'A390'),
  ('Artega', 'GT'),
  ('Aston Martin', 'Cygnet'),
  ('Aston Martin', 'DBS'),
  ('Aston Martin', 'DBS GT Zagato'),
  ('Aston Martin', 'Lagonda Taraf'),
  ('Aston Martin', 'One-77'),
  ('Aston Martin', 'V12 Speedster'),
  ('Aston Martin', 'V12 Zagato'),
  ('Aston Martin', 'Valiant'),
  ('Aston Martin', 'Valour'),
  ('Aston Martin', 'Vanquish Zagato'),
  ('Aston Martin', 'Virage'),
  ('Aston Martin', 'Vulcan'),
  ('Audi', 'A3 Cabriolet'),
  ('Audi', 'A3 Sportback TFSI e'),
  ('Audi', 'A4 Avant'),
  ('Audi', 'A4 allroad'),
  ('Audi', 'A5 Cabriolet'),
  ('Audi', 'A5 Limousine e-hybrid'),
  ('Audi', 'A5 Sportback'),
  ('Audi', 'A6 Avant'),
  ('Audi', 'A6 Avant e-hybrid'),
  ('Audi', 'A6 Limousine'),
  ('Audi', 'A6 Limousine e-hybrid'),
  ('Audi', 'A6 allroad'),
  ('Audi', 'Q3 Sportback e-hybrid'),
  ('Audi', 'Q3 e-hybrid'),
  ('Audi', 'Q5 Sportback e-hybrid'),
  ('Audi', 'Q5 e-hybrid'),
  ('Audi', 'RS 5 Sportback'),
  ('Audi', 'RS Q3 Sportback'),
  ('Audi', 'RS e-tron GT'),
  ('Audi', 'S e-tron GT'),
  ('Audi', 'S3 Limousine'),
  ('Audi', 'S3 Sportback'),
  ('Audi', 'S5 Avant'),
  ('Audi', 'S5 Limousine'),
  ('Audi', 'S6 Avant e-tron'),
  ('Audi', 'S6 Sportback e-tron'),
  ('Audi', 'SQ5 Sportback'),
  ('Audi', 'SQ8 Sportback e-tron'),
  ('Audi', 'SQ8 e-tron'),
  ('Audi', 'e-tron S'),
  ('Audi', 'e-tron S Sportback'),
  ('BMW', '114d'),
  ('BMW', '114i'),
  ('BMW', '116'),
  ('BMW', '120'),
  ('BMW', '123d'),
  ('BMW', '128ti'),
  ('BMW', '135i'),
  ('BMW', '1M Coupé'),
  ('BMW', '20 xDrive'),
  ('BMW', '214d'),
  ('BMW', '216d'),
  ('BMW', '216i'),
  ('BMW', '220'),
  ('BMW', '223d'),
  ('BMW', '223i'),
  ('BMW', '225e'),
  ('BMW', '230e'),
  ('BMW', '316d'),
  ('BMW', '320e'),
  ('BMW', '325i'),
  ('BMW', '328i'),
  ('BMW', '428i'),
  ('BMW', '520e'),
  ('BMW', '523i'),
  ('BMW', '525d'),
  ('BMW', '528i'),
  ('BMW', '535i'),
  ('BMW', '550e'),
  ('BMW', '620d'),
  ('BMW', '740e'),
  ('BMW', '750d'),
  ('BMW', '760i'),
  ('BMW', 'ActiveHybrid 3'),
  ('BMW', 'ActiveHybrid 5'),
  ('BMW', 'ActiveHybrid 7'),
  ('BMW', 'ActiveHybrid X6'),
  ('BMW', 'M135'),
  ('BMW', 'M235'),
  ('BMW', 'M340d'),
  ('BMW', 'M440d'),
  ('BMW', 'M50'),
  ('BMW', 'M50d'),
  ('BMW', 'M550d'),
  ('BMW', 'M550i'),
  ('BMW', 'M760e'),
  ('BMW', 'XM'),
  ('BMW', 'sDrive16d'),
  ('BMW', 'sDrive23i'),
  ('BMW', 'sDrive25d'),
  ('BMW', 'sDrive28i'),
  ('BMW', 'sDrive30i'),
  ('BMW', 'sDrive35i'),
  ('BMW', 'xDrive18d'),
  ('BMW', 'xDrive23d'),
  ('BMW', 'xDrive23i'),
  ('BMW', 'xDrive25d'),
  ('BMW', 'xDrive28i'),
  ('BMW', 'xDrive30e'),
  ('BMW', 'xDrive35d'),
  ('BMW', 'xDrive35i'),
  ('BMW', 'xDrive40e'),
  ('BMW', 'xDrive50e'),
  ('BMW', 'xDrive50i'),
  ('BYD', 'Atto 2'),
  ('BYD', 'Atto 3'),
  ('BYD', 'Dolphin'),
  ('BYD', 'Dolphin G'),
  ('BYD', 'Dolphin Surf'),
  ('BYD', 'ETP3'),
  ('BYD', 'Han'),
  ('BYD', 'Seal'),
  ('BYD', 'Seal 6 DM-i'),
  ('BYD', 'Seal U'),
  ('BYD', 'Sealion 7'),
  ('BYD', 'Tang'),
  ('BYD', 'e6'),
  ('Bentley', 'Azure'),
  ('Bentley', 'Brooklands'),
  ('Bentley', 'Continental Supersports'),
  ('Bugatti', 'Brouillard'),
  ('Bugatti', 'Tourbillon'),
  ('Cadillac', 'Escalade'),
  ('Cadillac', 'SRX'),
  ('Caterham', 'Seven'),
  ('Chevrolet', 'Aveo'),
  ('Chevrolet', 'Camaro'),
  ('Chevrolet', 'Captiva'),
  ('Chevrolet', 'Corvette'),
  ('Chevrolet', 'Cruze'),
  ('Chevrolet', 'Epica'),
  ('Chevrolet', 'Lacetti'),
  ('Chevrolet', 'Matiz'),
  ('Chevrolet', 'Nubira'),
  ('Chevrolet', 'Volt'),
  ('Chrysler', '300C'),
  ('Chrysler', 'Grand Voyager'),
  ('Chrysler', 'PT Cruiser'),
  ('Chrysler', 'Sebring'),
  ('Citroën', 'C-Crosser'),
  ('Citroën', 'C-Elysée'),
  ('Citroën', 'C-Zero'),
  ('Citroën', 'C1'),
  ('Citroën', 'C3 Pluriel'),
  ('Citroën', 'C4 Aircross'),
  ('Citroën', 'C4 Cactus'),
  ('Citroën', 'C5'),
  ('Citroën', 'C6'),
  ('Citroën', 'C8'),
  ('Citroën', 'DS4'),
  ('Citroën', 'DS5'),
  ('Citroën', 'Grand C4 Picasso'),
  ('Citroën', 'Grand C4 SpaceTourer'),
  ('Citroën', 'Holidays'),
  ('Citroën', 'Nemo'),
  ('Citroën', 'Xsara Picasso'),
  ('Cupra', 'Raval'),
  ('DS', '4 Crossback'),
  ('DS', '7'),
  ('DS', 'N°4'),
  ('Daihatsu', 'Charade'),
  ('Daihatsu', 'Copen'),
  ('Daihatsu', 'Materia'),
  ('Daihatsu', 'Sirion'),
  ('Daihatsu', 'Terios'),
  ('Daihatsu', 'Trevis'),
  ('Dodge', 'Avenger'),
  ('Dodge', 'Caliber'),
  ('Dodge', 'Challenger'),
  ('Dodge', 'Charger'),
  ('Dodge', 'Durango'),
  ('Dodge', 'Journey'),
  ('Dodge', 'Nitro'),
  ('Donkervoort', 'D8'),
  ('Donkervoort', 'P24 RS'),
  ('Ferrari', '296 Speciale'),
  ('Ferrari', '458 Speciale'),
  ('Ferrari', '599'),
  ('Ferrari', '612 Scaglietti'),
  ('Ferrari', '812 Competizione'),
  ('Ferrari', '849 Testarossa'),
  ('Ferrari', 'Amalfi'),
  ('Ferrari', 'California'),
  ('Ferrari', 'F12tdf'),
  ('Ferrari', 'Portofino M'),
  ('Ferrari', 'SF90 XX Stradale'),
  ('Fiat', '500 Hybrid'),
  ('Fiat', 'Bravo'),
  ('Fiat', 'Croma'),
  ('Fiat', 'Ducato'),
  ('Fiat', 'Grande Punto'),
  ('Fiat', 'Idea'),
  ('Fiat', 'Multipla'),
  ('Fiat', 'Punto Evo'),
  ('Fiat', 'Sedici'),
  ('Fisker', 'Karma'),
  ('Fisker', 'Ocean'),
  ('Ford', 'Bronco'),
  ('Ford', 'F-150 Lightning'),
  ('Ford', 'Fusion'),
  ('Ford', 'Grand C-MAX'),
  ('Ford', 'Grand Tourneo Connect'),
  ('Ford', 'Ranger Raptor'),
  ('Ford', 'Transit'),
  ('Ginetta', 'Akula'),
  ('Ginetta', 'G40'),
  ('HiPhi', 'Y'),
  ('Honda', 'Civic Type R'),
  ('Honda', 'Prelude'),
  ('Honda', 'Super-N'),
  ('Hyundai', 'Elantra'),
  ('Hyundai', 'Genesis'),
  ('Hyundai', 'Grand Santa Fe'),
  ('Hyundai', 'H-1 Cargo'),
  ('Hyundai', 'H350'),
  ('Hyundai', 'Matrix'),
  ('Hyundai', 'Sonata'),
  ('Hyundai', 'i20 Coupé'),
  ('Hyundai', 'i30 Fastback'),
  ('Infiniti', 'EX'),
  ('Infiniti', 'FX'),
  ('Infiniti', 'M'),
  ('Jaecoo', '5'),
  ('Jaecoo', '7'),
  ('Jaecoo', '8'),
  ('Jaguar', 'XK'),
  ('Jeep', 'Commander'),
  ('Jeep', 'Gladiator'),
  ('KTM', 'X-Bow'),
  ('Kia', 'Cee''d SW'),
  ('Kia', 'Ceed GT'),
  ('Kia', 'EV2'),
  ('Kia', 'Magentis'),
  ('Kia', 'Optima'),
  ('Kia', 'Optima Sportswagon'),
  ('Kia', 'ProCeed'),
  ('Kia', 'ProCeed GT'),
  ('Kia', 'Rio'),
  ('Kia', 'Venga'),
  ('Kia', 'e-Niro'),
  ('Kia', 'e-Soul'),
  ('Koenigsegg', 'One:1'),
  ('Koenigsegg', 'Sadair''s Spear'),
  ('Lada', 'Granta'),
  ('Lada', 'Niva'),
  ('Lada', 'Taiga'),
  ('Lamborghini', 'Essenza SCV12'),
  ('Lamborghini', 'Fenomeno'),
  ('Lamborghini', 'Gallardo'),
  ('Lamborghini', 'Murciélago'),
  ('Lamborghini', 'Sesto Elemento'),
  ('Lamborghini', 'Veneno'),
  ('Lancia', 'Delta'),
  ('Lancia', 'Flavia'),
  ('Lancia', 'Musa'),
  ('Lancia', 'Phedra'),
  ('Lancia', 'Thema'),
  ('Land Rover', 'Freelander'),
  ('Leapmotor', 'B03X'),
  ('Leapmotor', 'B05'),
  ('Leapmotor', 'B10'),
  ('Lexus', 'GS'),
  ('Lexus', 'IS'),
  ('Lexus', 'LFA'),
  ('Ligier', 'IXO'),
  ('Ligier', 'JS 50'),
  ('Ligier', 'JS 50 L'),
  ('Lotus', '2-Eleven'),
  ('Lotus', 'Europa'),
  ('MG', 'Cyberster'),
  ('MG', 'EHS'),
  ('MG', 'GS'),
  ('MG', 'HS'),
  ('MG', 'IM5'),
  ('MG', 'IM6'),
  ('MG', 'MG3'),
  ('MG', 'MG4'),
  ('MG', 'MG5'),
  ('MG', 'MG6'),
  ('MG', 'Marvel R'),
  ('MG', 'S5 EV'),
  ('MG', 'S9'),
  ('MG', 'ZS'),
  ('MINI', 'Aceman John Cooper Works'),
  ('MINI', 'Cabrio Cooper S'),
  ('MINI', 'Cabrio John Cooper Works'),
  ('MINI', 'Clubvan'),
  ('MINI', 'Cooper'),
  ('MINI', 'Cooper S 5-Türer'),
  ('MINI', 'Coupé Cooper S'),
  ('MINI', 'Coupé John Cooper Works'),
  ('MINI', 'John Cooper Works Electric'),
  ('MINI', 'John Cooper Works GP'),
  ('MINI', 'One'),
  ('MINI', 'Paceman Cooper S'),
  ('MINI', 'Paceman John Cooper Works'),
  ('MINI', 'Roadster Cooper S'),
  ('MINI', 'Roadster John Cooper Works'),
  ('Mahindra', 'Goa'),
  ('Mahindra', 'KUV100'),
  ('Mahindra', 'XUV500'),
  ('Maserati', 'GT2 Stradale'),
  ('Maserati', 'MCPura'),
  ('Maxus', 'Deliver 7'),
  ('Maxus', 'Deliver 9'),
  ('Maxus', 'Euniq 5'),
  ('Maxus', 'Euniq 6'),
  ('Maxus', 'Mifa 7'),
  ('Maxus', 'Mifa 9'),
  ('Maxus', 'T60 Max'),
  ('Maxus', 'T90 EV'),
  ('Maxus', 'eDeliver 3'),
  ('Maxus', 'eDeliver 5'),
  ('Maxus', 'eDeliver 7'),
  ('Maxus', 'eDeliver 9'),
  ('Maxus', 'eTerron 9'),
  ('Mazda', '6e'),
  ('Mazda', 'BT-50'),
  ('Mazda', 'CX-7'),
  ('Mazda', 'RX-8'),
  ('McLaren', '12C'),
  ('McLaren', '540C'),
  ('McLaren', '570GT'),
  ('McLaren', '570S'),
  ('McLaren', '600LT'),
  ('McLaren', '620R'),
  ('McLaren', '650S'),
  ('McLaren', '675LT'),
  ('McLaren', '720S'),
  ('McLaren', '750S'),
  ('McLaren', '765LT'),
  ('McLaren', 'GTS'),
  ('McLaren', 'W1'),
  ('Mercedes', 'A 250 e'),
  ('Mercedes', 'AMG CLE 53'),
  ('Mercedes', 'AMG CLS 63'),
  ('Mercedes', 'AMG EQE 43'),
  ('Mercedes', 'AMG EQE 53'),
  ('Mercedes', 'AMG EQS 53'),
  ('Mercedes', 'AMG G 65'),
  ('Mercedes', 'AMG GLE 43'),
  ('Mercedes', 'AMG ONE'),
  ('Mercedes', 'AMG SL 43'),
  ('Mercedes', 'AMG SL 55'),
  ('Mercedes', 'AMG SLC 43'),
  ('Mercedes', 'B 160'),
  ('Mercedes', 'B 250 e'),
  ('Mercedes', 'C 160'),
  ('Mercedes', 'C 300 de'),
  ('Mercedes', 'C 350'),
  ('Mercedes', 'C 400'),
  ('Mercedes', 'CL'),
  ('Mercedes', 'CLA 250 e'),
  ('Mercedes', 'CLA 350'),
  ('Mercedes', 'CLC'),
  ('Mercedes', 'CLS 250 d'),
  ('Mercedes', 'CLS 400'),
  ('Mercedes', 'CLS 500'),
  ('Mercedes', 'CLS Shooting Brake'),
  ('Mercedes', 'E 250'),
  ('Mercedes', 'E 300 de'),
  ('Mercedes', 'E 350 e'),
  ('Mercedes', 'E 450'),
  ('Mercedes', 'E 500'),
  ('Mercedes', 'G 400 d'),
  ('Mercedes', 'G 450 d'),
  ('Mercedes', 'G 580'),
  ('Mercedes', 'GL'),
  ('Mercedes', 'GLA 160'),
  ('Mercedes', 'GLA 250 e'),
  ('Mercedes', 'GLC 300 de'),
  ('Mercedes', 'GLC 350 e'),
  ('Mercedes', 'GLC 400 d'),
  ('Mercedes', 'GLC 400 e'),
  ('Mercedes', 'GLE 250 d'),
  ('Mercedes', 'GLE 350 de'),
  ('Mercedes', 'GLE 400 e'),
  ('Mercedes', 'GLE 500 e'),
  ('Mercedes', 'GLK'),
  ('Mercedes', 'ML'),
  ('Mercedes', 'Marco Polo'),
  ('Mercedes', 'Maybach EQS 680 SUV'),
  ('Mercedes', 'Maybach GLS 600'),
  ('Mercedes', 'Maybach S 580'),
  ('Mercedes', 'Maybach S 600'),
  ('Mercedes', 'Maybach S 650'),
  ('Mercedes', 'Maybach S 680'),
  ('Mercedes', 'R-Klasse'),
  ('Mercedes', 'S 500 e'),
  ('Mercedes', 'S 560 e'),
  ('Mercedes', 'S 580 e'),
  ('Mercedes', 'S 600'),
  ('Mercedes', 'SL 350'),
  ('Mercedes', 'SLC 250 d'),
  ('Mercedes', 'SLS AMG'),
  ('Mercedes', 'Viano'),
  ('Mercedes', 'Vito'),
  ('Mercedes', 'eCitan'),
  ('Mercedes', 'eSprinter'),
  ('Mercedes', 'eVito'),
  ('Micro', 'Microlino Lite'),
  ('Mitsubishi', 'Grandis'),
  ('Mitsubishi', 'Lancer Evolution'),
  ('Mobilize', 'Bento'),
  ('Morgan', 'Aero Coupe'),
  ('Morgan', 'Aero SuperSports'),
  ('Nissan', 'Interstar'),
  ('Nissan', 'NV200'),
  ('Nissan', 'NV250'),
  ('Nissan', 'NV300'),
  ('Nissan', 'NV400'),
  ('Nissan', 'Note'),
  ('Nissan', 'Pixo'),
  ('Nissan', 'Primastar'),
  ('Nissan', 'Pulsar'),
  ('Nissan', 'Qashqai+2'),
  ('Nissan', 'e-NV200'),
  ('Omoda', '5'),
  ('Omoda', '7'),
  ('Omoda', '9'),
  ('Omoda', 'E5'),
  ('Opel', 'Astra H'),
  ('Opel', 'Astra H OPC'),
  ('Opel', 'Astra J OPC'),
  ('Opel', 'Combo C'),
  ('Opel', 'Combo Life'),
  ('Opel', 'Corsa D'),
  ('Opel', 'Corsa D OPC'),
  ('Opel', 'Corsa E OPC'),
  ('Opel', 'Insignia A OPC'),
  ('Opel', 'Meriva A'),
  ('Opel', 'Mokka GSE'),
  ('Opel', 'Movano A'),
  ('Opel', 'Vivaro A'),
  ('Opel', 'Zafira'),
  ('Opel', 'Zafira B'),
  ('Opel', 'Zafira B OPC'),
  ('Opel', 'Zafira Life'),
  ('Pagani', 'Huayra'),
  ('Pagani', 'Zonda'),
  ('Peugeot', '107'),
  ('Peugeot', '206+'),
  ('Peugeot', '207'),
  ('Peugeot', '207 CC'),
  ('Peugeot', '207 SW'),
  ('Peugeot', '301'),
  ('Peugeot', '308 CC'),
  ('Peugeot', '4007'),
  ('Peugeot', '407'),
  ('Peugeot', '407 SW'),
  ('Peugeot', '508 PSE'),
  ('Peugeot', '508 RXH'),
  ('Peugeot', '508 SW'),
  ('Peugeot', '607'),
  ('Peugeot', '807'),
  ('Peugeot', 'Bipper Tepee'),
  ('Peugeot', 'E-2008'),
  ('Peugeot', 'E-408'),
  ('Peugeot', 'E-Boxer'),
  ('Peugeot', 'E-Expert'),
  ('Peugeot', 'E-Partner'),
  ('Peugeot', 'E-Rifter'),
  ('Peugeot', 'E-Traveller'),
  ('Peugeot', 'Expert'),
  ('Peugeot', 'Partner'),
  ('Peugeot', 'RCZ R'),
  ('Piaggio', 'Ape'),
  ('Piaggio', 'Porter NP6'),
  ('Piaggio', 'Quargo'),
  ('Pininfarina', 'B95'),
  ('Porsche', '718 Boxster T'),
  ('Porsche', '718 Cayman GT4 RS'),
  ('Porsche', '718 Cayman T'),
  ('Porsche', '718 Spyder RS'),
  ('Porsche', '911 Carrera T'),
  ('Porsche', '911 Dakar'),
  ('Porsche', '911 GT2 RS'),
  ('Porsche', '911 R'),
  ('Porsche', '911 S/T'),
  ('Porsche', '911 Speedster'),
  ('Porsche', '911 Sport Classic'),
  ('Porsche', '911 Targa'),
  ('Porsche', 'Cayenne Coupé'),
  ('Porsche', 'Cayenne E-Hybrid'),
  ('Porsche', 'Cayenne Electric'),
  ('Porsche', 'Cayenne S E-Hybrid'),
  ('Porsche', 'Cayenne Turbo E-Hybrid'),
  ('Porsche', 'Cayenne Turbo Electric'),
  ('Porsche', 'Cayenne Turbo GT'),
  ('Porsche', 'Macan 4'),
  ('Porsche', 'Macan 4S'),
  ('Porsche', 'Macan T'),
  ('Porsche', 'Panamera 4 E-Hybrid'),
  ('Porsche', 'Panamera 4S E-Hybrid'),
  ('Porsche', 'Panamera S'),
  ('Porsche', 'Panamera S E-Hybrid'),
  ('Porsche', 'Panamera Sport Turismo'),
  ('Porsche', 'Panamera Turbo E-Hybrid'),
  ('Porsche', 'Panamera Turbo S'),
  ('Porsche', 'Taycan 4S'),
  ('Porsche', 'Taycan Cross Turismo'),
  ('Porsche', 'Taycan GTS'),
  ('Porsche', 'Taycan Sport Turismo'),
  ('Porsche', 'Taycan Turbo'),
  ('Porsche', 'Taycan Turbo GT'),
  ('Porsche', 'Taycan Turbo S'),
  ('Proton', 'Gen-2'),
  ('RAM', '1500'),
  ('RAM', '2500'),
  ('RAM', '3500'),
  ('Renault', 'Clio GT'),
  ('Renault', 'Fluence'),
  ('Renault', 'Grand Espace'),
  ('Renault', 'Grand Kangoo'),
  ('Renault', 'Grand Modus'),
  ('Renault', 'Grand Scenic'),
  ('Renault', 'Megane RS Trophy-R'),
  ('Renault', 'Modus'),
  ('Renault', 'Scenic E-Tech Electric'),
  ('Renault', 'Twingo GT'),
  ('Renault', 'Twingo RS'),
  ('Renault', 'Wind'),
  ('Rimac', 'Concept One'),
  ('Rimac', 'Nevera R'),
  ('Saab', '9-3'),
  ('Saab', '9-5'),
  ('Seat', 'Exeo'),
  ('Seres', '3'),
  ('Seres', '5'),
  ('SsangYong', 'Actyon'),
  ('SsangYong', 'Korando e-Motion'),
  ('SsangYong', 'Kyron'),
  ('SsangYong', 'Musso Grand'),
  ('SsangYong', 'Rodius'),
  ('SsangYong', 'Torres EVX'),
  ('Subaru', 'E-Outback'),
  ('Subaru', 'Tribeca'),
  ('Subaru', 'Uncharted'),
  ('Subaru', 'WRX STI'),
  ('Subaru', 'XV'),
  ('Suzuki', 'Alto'),
  ('Suzuki', 'Kizashi'),
  ('Suzuki', 'Splash'),
  ('Suzuki', 'Swift Sport'),
  ('Suzuki', 'e Vitara'),
  ('Tata', 'Vista'),
  ('Tata', 'Xenon'),
  ('Toyota', 'Auris Touring Sports'),
  ('Toyota', 'Avensis Touring Sports'),
  ('Toyota', 'Hiace'),
  ('Toyota', 'Prius Plus'),
  ('Toyota', 'Yaris GRMN'),
  ('Vauxhall', 'Astra H'),
  ('Vauxhall', 'Astra H VXR'),
  ('Vauxhall', 'Astra J VXR'),
  ('Vauxhall', 'Combo C'),
  ('Vauxhall', 'Combo Life'),
  ('Vauxhall', 'Corsa D'),
  ('Vauxhall', 'Corsa D VXR'),
  ('Vauxhall', 'Corsa E VXR'),
  ('Vauxhall', 'Insignia A VXR'),
  ('Vauxhall', 'Meriva A'),
  ('Vauxhall', 'Mokka GSE'),
  ('Vauxhall', 'Movano A'),
  ('Vauxhall', 'VXR8'),
  ('Vauxhall', 'Vivaro A'),
  ('Vauxhall', 'Vivaro Life'),
  ('Vauxhall', 'Zafira B'),
  ('Vauxhall', 'Zafira B VXR'),
  ('Volkswagen', 'Arteon R Shooting Brake'),
  ('Volkswagen', 'Arteon Shooting Brake'),
  ('Volkswagen', 'Caddy California'),
  ('Volkswagen', 'Caddy Cargo'),
  ('Volkswagen', 'Fox'),
  ('Volkswagen', 'Golf Alltrack'),
  ('Volkswagen', 'Golf Cabriolet'),
  ('Volkswagen', 'Golf GTD Variant'),
  ('Volkswagen', 'Golf GTI Cabriolet'),
  ('Volkswagen', 'Golf GTI Clubsport'),
  ('Volkswagen', 'Golf GTI TCR'),
  ('Volkswagen', 'Golf Plus'),
  ('Volkswagen', 'Golf R Cabriolet'),
  ('Volkswagen', 'Golf Sportsvan'),
  ('Volkswagen', 'ID. Buzz GTX'),
  ('Volkswagen', 'ID. Polo'),
  ('Volkswagen', 'ID.3 GTX'),
  ('Volkswagen', 'ID.4 GTX'),
  ('Volkswagen', 'ID.5 GTX'),
  ('Volkswagen', 'ID.7 GTX'),
  ('Volkswagen', 'ID.7 GTX Tourer'),
  ('Volkswagen', 'Passat Alltrack'),
  ('Volkswagen', 'Passat Variant'),
  ('Volkswagen', 'Polo R WRC'),
  ('Volkswagen', 'Scirocco R'),
  ('Volkswagen', 'The Beetle Cabriolet'),
  ('Volkswagen', 'Tiguan Allspace'),
  ('Volkswagen', 'Touareg R'),
  ('Volkswagen', 'XL1'),
  ('Volkswagen', 'e-Caravelle'),
  ('Volkswagen', 'e-Crafter'),
  ('Volkswagen', 'e-Golf'),
  ('Volkswagen', 'e-Transporter'),
  ('Volkswagen', 'e-up!'),
  ('Volkswagen', 'up! GTI'),
  ('Volvo', 'C30'),
  ('Volvo', 'C70'),
  ('Volvo', 'EX30 Cross Country'),
  ('Volvo', 'EX60'),
  ('Volvo', 'S40'),
  ('Volvo', 'S60 Cross Country'),
  ('Volvo', 'V40 Cross Country'),
  ('Volvo', 'V50'),
  ('Volvo', 'V60 Cross Country'),
  ('Volvo', 'V90 Cross Country'),
  ('Voyah', 'Courage'),
  ('Voyah', 'Dream'),
  ('XPeng', 'G3'),
  ('XPeng', 'G7'),
  ('XPeng', 'P5'),
  ('XPeng', 'X9'),
  ('e.GO Mobile', 'e.wave X'),
  ('Škoda', 'Enyaq Coupé'),
  ('Škoda', 'Epiq'),
  ('Škoda', 'Rapid Spaceback');

insert into public.models (make_id, name, normalized_name, source)
select mk.id, a.model, public.normalize_vehicle_name(a.model), 'catalog_extension_2010_onwards'
from tmp_catalog_additions a
join public.makes mk
  on mk.normalized_name = public.normalize_vehicle_name(a.make)
on conflict (make_id, normalized_name) do nothing;

drop table tmp_catalog_additions;
