-- Generated by src/scripts/import-variant-catalog.mjs — do not edit by hand.
begin;

-- ---------- models the CSV never carried ----------
with m(make, name) as (values
    ('BMW','2 Series Coupé'),
    ('BMW','2 Series Cabriolet'),
    ('BMW','2 Series Active Tourer'),
    ('BMW','2 Series Gran Tourer'),
    ('BMW','2 Series Gran Coupé'),
    ('BMW','3 Series Touring'),
    ('BMW','3 Series Gran Turismo'),
    ('BMW','4 Series Coupé'),
    ('BMW','4 Series Cabriolet'),
    ('BMW','4 Series Gran Coupé'),
    ('BMW','5 Series Touring'),
    ('BMW','5 Series Gran Turismo'),
    ('BMW','6 Series Coupé'),
    ('BMW','6 Series Cabriolet'),
    ('BMW','6 Series Gran Coupé'),
    ('BMW','6 Series Gran Turismo'),
    ('BMW','7 Series'),
    ('BMW','8 Series Coupé'),
    ('BMW','8 Series Cabriolet'),
    ('BMW','8 Series Gran Coupé')
)
insert into public.models (make_id, name, source)
select mk.id, m.name, 'catalog_variants_v1'
from m
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(m.make)
on conflict (make_id, normalized_name) do nothing;

-- ---------- variants ----------
with g(make, models, variants) as (values
    ('Audi',array['A1','A1 Sportback'],array['1.0 TFSI','1.2 TFSI','1.4 TFSI','1.6 TDI','2.0 TDI','25 TFSI','30 TFSI','35 TFSI','40 TFSI']),
    ('Audi',array['A1 allstreet / citycarver'],array['25 TFSI','30 TFSI','35 TFSI']),
    ('Audi',array['A3','A3 Sportback'],array['1.0 TFSI','1.2 TFSI','1.4 TFSI','1.5 TFSI','1.6 TDI','1.8 TFSI','1.8 TFSI quattro','2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','30 TDI','30 TFSI','35 TDI','35 TFSI','40 TDI quattro','40 TFSI quattro']),
    ('Audi',array['A3 Limousine'],array['1.0 TFSI','1.4 TFSI','1.5 TFSI','1.6 TDI','1.8 TFSI quattro','2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','30 TDI','30 TFSI','35 TDI','35 TFSI','40 TDI quattro','40 TFSI quattro']),
    ('Audi',array['A3 Cabriolet'],array['1.4 TFSI','1.8 TFSI','1.8 TFSI quattro','2.0 TDI','2.0 TFSI quattro','30 TFSI','35 TFSI']),
    ('Audi',array['A3 allstreet'],array['30 TDI','30 TFSI','35 TDI','35 TFSI']),
    ('Audi',array['A3 allstreet TFSI e'],array['40 TFSI e']),
    ('Audi',array['A3 Sportback TFSI e'],array['40 TFSI e','45 TFSI e']),
    ('Audi',array['A4','A4 Avant'],array['1.4 TFSI','1.8 TFSI','2.0 TDI','2.0 TDI quattro','2.0 TFSI','2.0 TFSI quattro','3.0 TDI (V6)','3.0 TDI quattro','30 TDI','35 TDI','35 TFSI','40 TDI','40 TDI quattro','40 TFSI','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['A4 allroad'],array['2.0 TDI quattro','2.0 TFSI quattro','3.0 TDI quattro','40 TDI quattro','45 TFSI quattro']),
    ('Audi',array['A5','A5 Sportback'],array['1.8 TFSI','2.0 TDI','2.0 TDI quattro','2.0 TFSI','2.0 TFSI quattro','3.0 TDI quattro','35 TDI','35 TFSI','40 TDI quattro','40 TFSI','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['A5 Cabriolet'],array['1.8 TFSI','2.0 TDI','2.0 TFSI quattro','3.0 TDI quattro','35 TFSI','40 TFSI','45 TFSI quattro']),
    ('Audi',array['A5 Avant','A5 Limousine'],array['35 TDI','35 TFSI','40 TDI quattro','40 TFSI','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['A6','A6 Avant'],array['2.0 TDI','2.0 TFSI','3.0 TDI (V6)','3.0 TDI quattro','3.0 TFSI quattro','35 TDI','40 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI quattro','55 TFSI e quattro']),
    ('Audi',array['A6 Limousine'],array['35 TDI','40 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI quattro']),
    ('Audi',array['A6 allroad'],array['3.0 TDI quattro','45 TDI quattro','50 TDI quattro','55 TDI quattro']),
    ('Audi',array['A5 Avant e-hybrid','A5 Limousine e-hybrid','A6 Avant e-hybrid','A6 Limousine e-hybrid','Q5 e-hybrid','Q5 Sportback e-hybrid'],array['299 PS','367 PS']),
    ('Audi',array['A6 e-tron','A6 Avant e-tron','A6 Sportback e-tron','Q6 e-tron','Q6 Sportback e-tron','Q6 SUV e-tron'],array['performance','quattro']),
    ('Audi',array['A7'],array['3.0 TDI quattro','3.0 TFSI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI quattro','55 TFSI e quattro']),
    ('Audi',array['A8'],array['3.0 TDI quattro','4.0 TFSI quattro','50 TDI quattro','55 TFSI quattro','60 TFSI e quattro','L 50 TDI quattro','L 55 TFSI quattro','L 60 TFSI e quattro']),
    ('Audi',array['Q2'],array['1.0 TFSI','1.4 TFSI','1.6 TDI','2.0 TDI quattro','30 TDI','30 TFSI','35 TDI quattro','35 TFSI']),
    ('Audi',array['Q3'],array['1.4 TFSI','2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','35 TDI','35 TDI quattro','35 TFSI','40 TDI quattro','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['Q3 Sportback'],array['35 TDI','35 TDI quattro','35 TFSI','40 TDI quattro','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['Q3 e-hybrid','Q3 Sportback e-hybrid'],array['45 TFSI e']),
    ('Audi',array['Q4 e-tron','Q4 Sportback e-tron'],array['35 e-tron','40 e-tron','45 e-tron','45 e-tron quattro','50 e-tron quattro','55 e-tron quattro']),
    ('Audi',array['Q5'],array['2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','3.0 TDI quattro','35 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI e quattro']),
    ('Audi',array['Q5 Sportback'],array['35 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI e quattro']),
    ('Audi',array['Q7'],array['3.0 TDI quattro','3.0 TFSI quattro','45 TDI quattro','50 TDI quattro','55 TFSI quattro','60 TFSI e quattro']),
    ('Audi',array['Q8'],array['45 TDI quattro','50 TDI quattro','55 TFSI quattro','60 TFSI e quattro']),
    ('Audi',array['Q8 e-tron','Q8 Sportback e-tron','e-tron','e-tron Sportback'],array['50 quattro','55 quattro']),
    ('Audi',array['e-tron S','e-tron S Sportback','SQ8 e-tron','SQ8 Sportback e-tron'],array['503 PS']),
    ('Audi',array['e-tron GT'],array['quattro','performance quattro']),
    ('Audi',array['S e-tron GT'],array['679 PS']),
    ('Audi',array['RS e-tron GT'],array['598 PS','performance']),
    ('Audi',array['R8'],array['V10','V10 plus','V10 performance quattro','V10 RWD','V10 Spyder','GT RWD']),
    ('Audi',array['TT'],array['1.8 TFSI','2.0 TDI ultra','2.0 TFSI','2.0 TFSI quattro','40 TFSI','45 TFSI quattro']),
    ('Audi',array['TTS','S1','S3','S3 Sportback','S3 Limousine','SQ2','SQ3'],array['2.0 TFSI quattro']),
    ('Audi',array['TT RS','RS3','RS 3 Sportback','RS 3 Limousine','RSQ3','RS Q3 Sportback'],array['2.5 TFSI quattro']),
    ('Audi',array['S4','S5','S5 Avant','S5 Limousine','SQ5'],array['3.0 TDI quattro','3.0 TFSI quattro']),
    ('Audi',array['SQ5 Sportback'],array['3.0 TDI quattro']),
    ('Audi',array['S6','S7'],array['3.0 TDI quattro','4.0 TFSI quattro']),
    ('Audi',array['S8'],array['4.0 TFSI quattro']),
    ('Audi',array['S6 Avant e-tron','S6 Sportback e-tron'],array['551 PS']),
    ('Audi',array['SQ6 Sportback e-tron','SQ6 SUV e-tron'],array['489 PS']),
    ('Audi',array['SQ7','SQ8'],array['4.0 TDI quattro','4.0 TFSI quattro']),
    ('Audi',array['RS4','RS5'],array['2.9 TFSI quattro','4.2 FSI quattro']),
    ('Audi',array['RS 5 Sportback'],array['2.9 TFSI quattro']),
    ('Audi',array['RS6','RS7','RSQ8'],array['4.0 TFSI quattro','4.0 TFSI quattro performance']),
    ('BMW',array['1 Series'],array['114d','114i','116','116d','116i','118d','118i','120','120d','120i','123d','125d','125i','128ti','135i','M135','M135i','M140i']),
    ('BMW',array['2 Series Coupé'],array['218d','218i','220','220d','220i','225d','228i','230i','M235','M235i','M240i']),
    ('BMW',array['2 Series Cabriolet'],array['218d','218i','220d','220i','228i','230i','M235i','M240i']),
    ('BMW',array['2 Series Active Tourer'],array['214d','216d','216i','218d','218i','220d','220i','223d','223i','225e','225i','225xe','230e']),
    ('BMW',array['2 Series Gran Tourer'],array['214d','216d','216i','218d','218i','220d','220i']),
    ('BMW',array['2 Series Gran Coupé'],array['216d','218d','218i','220d','220i','228i','M235i']),
    ('BMW',array['3 Series'],array['316d','316i','318d','318i','320d','320e','320i','325d','325i','328i','330d','330e','330i','335d','335i','340i','M340d','M340i']),
    ('BMW',array['3 Series Touring'],array['316d','316i','318d','318i','320d','320e','320i','325d','328i','330d','330e','330i','335d','335i','340i','M340d','M340i']),
    ('BMW',array['3 Series Gran Turismo'],array['318d','320d','320i','325d','328i','330d','330i','335d','335i','340i']),
    ('BMW',array['4 Series Coupé','4 Series Gran Coupé'],array['418d','418i','420d','420i','425d','428i','430d','430i','435d','435i','440i','M440d','M440i']),
    ('BMW',array['4 Series Cabriolet'],array['420d','420i','428i','430d','430i','435i','440i','M440i']),
    ('BMW',array['5 Series'],array['518d','520d','520e','520i','523i','525d','528i','530d','530e','530i','535d','535i','540d','540i','545e','550e','550i','M550d','M550i'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('BMW',array['5 Series Touring'],array['518d','520d','520i','525d','530d','530e','530i','535d','535i','540d','540i','M550d']),
    ('BMW',array['5 Series Gran Turismo'],array['520d','530d','535d','535i','550i']),
    ('BMW',array['6 Series Coupé','6 Series Cabriolet','6 Series Gran Coupé'],array['640d','640i','650i']),
    ('BMW',array['6 Series Gran Turismo'],array['620d','630d','630i','640d','640i']),
    ('BMW',array['7 Series'],array['730d','730i','740d','740e','740i','745e','750d','750e','750i','760i','M760e','M760i']),
    ('BMW',array['8 Series Coupé'],array['840d','840i','850i','M850i']),
    ('BMW',array['8 Series Cabriolet','8 Series Gran Coupé'],array['840d','840i','M850i']),
    ('BMW',array['X1'],array['sDrive16d','sDrive18d','sDrive18i','sDrive20d','sDrive20i','xDrive18d','xDrive20d','xDrive20i','xDrive23i','xDrive25d','xDrive25e','xDrive25i','xDrive28i','xDrive30e','M35i']),
    ('BMW',array['X2'],array['sDrive18d','sDrive18i','sDrive20i','sDrive25d','xDrive18d','xDrive20d','xDrive20i','xDrive25d','xDrive25e','M35i']),
    ('BMW',array['X3'],array['sDrive18d','sDrive20i','xDrive20d','xDrive20i','xDrive23d','xDrive25d','xDrive28i','xDrive30d','xDrive30e','xDrive30i','xDrive35d','xDrive35i','M40d','M40i']),
    ('BMW',array['X4'],array['xDrive20d','xDrive20i','xDrive28i','xDrive30d','xDrive30i','xDrive35d','xDrive35i','M40d','M40i']),
    ('BMW',array['X5'],array['sDrive25d','xDrive25d','xDrive30d','xDrive35i','xDrive40d','xDrive40e','xDrive40i','xDrive45e','xDrive50e','xDrive50i','M50d','M50i','M60i']),
    ('BMW',array['X6'],array['xDrive30d','xDrive35i','xDrive40d','xDrive40i','xDrive50i','M50d','M50i','M60i']),
    ('BMW',array['X7'],array['xDrive30d','xDrive40d','xDrive40i','M50d','M50i','M60i']),
    ('BMW',array['Z4'],array['sDrive18i','sDrive20i','sDrive23i','sDrive28i','sDrive30i','sDrive35i','M40i']),
    ('BMW',array['i3'],array['60 Ah','94 Ah','120 Ah']),
    ('BMW',array['i3s'],array['94 Ah','120 Ah']),
    ('BMW',array['i4'],array['eDrive35','eDrive40','xDrive40','M50']),
    ('BMW',array['i5','i5 Touring'],array['eDrive40','xDrive40','M60']),
    ('BMW',array['i7'],array['eDrive50','xDrive60','M70']),
    ('BMW',array['i8'],array['Coupé','Roadster']),
    ('BMW',array['iX'],array['xDrive40','xDrive50','M60']),
    ('BMW',array['iX1','iX2'],array['eDrive20','xDrive30']),
    ('BMW',array['iX3'],array['eDrive20','xDrive50','80 kWh']),
    ('BMW',array['M2'],array['3.0','Competition','CS']),
    ('BMW',array['M3'],array['3.0','Competition','Competition xDrive','CS']),
    ('BMW',array['M3 Touring'],array['Competition xDrive']),
    ('BMW',array['M4'],array['3.0','Competition','Competition xDrive','CS','CSL']),
    ('BMW',array['M5'],array['4.4 V8','Competition','CS']),
    ('BMW',array['M5 Touring'],array['4.4 V8']),
    ('BMW',array['M6'],array['4.4 V8','Competition','Gran Coupé']),
    ('BMW',array['M8'],array['Competition','Gran Coupé','Competition Gran Coupé']),
    ('BMW',array['X3 M','X4 M','X5 M','X6 M'],array['Competition']),
    ('BMW',array['XM'],array['653 PS']),
    ('BMW',array['XM 50e'],array['476 PS']),
    ('BMW',array['XM Label'],array['748 PS']),
    ('BMW',array['1M Coupé'],array['3.0']),
    ('BMW',array['ActiveHybrid 3','ActiveHybrid 5'],array['3.0']),
    ('BMW',array['ActiveHybrid 7','ActiveHybrid X6'],array['4.4 V8'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

-- ---------- remap: rows seeded as models that are really trims ----------
create temp table _remap on commit drop as
select * from (values
    ('BMW','114d','1 Series','114d'),
    ('BMW','114i','1 Series','114i'),
    ('BMW','116','1 Series','116'),
    ('BMW','116d','1 Series','116d'),
    ('BMW','116i','1 Series','116i'),
    ('BMW','118d','1 Series','118d'),
    ('BMW','118i','1 Series','118i'),
    ('BMW','120','1 Series','120'),
    ('BMW','120d','1 Series','120d'),
    ('BMW','120i','1 Series','120i'),
    ('BMW','123d','1 Series','123d'),
    ('BMW','125d','1 Series','125d'),
    ('BMW','125i','1 Series','125i'),
    ('BMW','128ti','1 Series','128ti'),
    ('BMW','135i','1 Series','135i'),
    ('BMW','M135','1 Series','M135'),
    ('BMW','M135i','1 Series','M135i'),
    ('BMW','M140i','1 Series','M140i'),
    ('BMW','214d','2 Series Active Tourer','214d'),
    ('BMW','216d','2 Series Active Tourer','216d'),
    ('BMW','216i','2 Series Active Tourer','216i'),
    ('BMW','218d','2 Series Coupé','218d'),
    ('BMW','218i','2 Series Coupé','218i'),
    ('BMW','220','2 Series Coupé','220'),
    ('BMW','220d','2 Series Coupé','220d'),
    ('BMW','220i','2 Series Coupé','220i'),
    ('BMW','220i Active Tourer','2 Series Active Tourer','220i'),
    ('BMW','223d','2 Series Active Tourer','223d'),
    ('BMW','223i','2 Series Active Tourer','223i'),
    ('BMW','225d','2 Series Coupé','225d'),
    ('BMW','225e','2 Series Active Tourer','225e'),
    ('BMW','225i','2 Series Active Tourer','225i'),
    ('BMW','225xe','2 Series Active Tourer','225xe'),
    ('BMW','228i','2 Series Coupé','228i'),
    ('BMW','230e','2 Series Active Tourer','230e'),
    ('BMW','230i','2 Series Coupé','230i'),
    ('BMW','M235','2 Series Coupé','M235'),
    ('BMW','M235i','2 Series Coupé','M235i'),
    ('BMW','M240i','2 Series Coupé','M240i'),
    ('BMW','316d','3 Series','316d'),
    ('BMW','316i','3 Series','316i'),
    ('BMW','318d','3 Series','318d'),
    ('BMW','318i','3 Series','318i'),
    ('BMW','320d','3 Series','320d'),
    ('BMW','320e','3 Series','320e'),
    ('BMW','320i','3 Series','320i'),
    ('BMW','325d','3 Series','325d'),
    ('BMW','325i','3 Series','325i'),
    ('BMW','328i','3 Series','328i'),
    ('BMW','330d','3 Series','330d'),
    ('BMW','330e','3 Series','330e'),
    ('BMW','330i','3 Series','330i'),
    ('BMW','335d','3 Series','335d'),
    ('BMW','335i','3 Series','335i'),
    ('BMW','340i','3 Series','340i'),
    ('BMW','M340d','3 Series','M340d'),
    ('BMW','M340d xDrive Touring','3 Series Touring','M340d'),
    ('BMW','M340i','3 Series','M340i'),
    ('BMW','418d','4 Series Coupé','418d'),
    ('BMW','418i','4 Series Coupé','418i'),
    ('BMW','420d','4 Series Coupé','420d'),
    ('BMW','420i','4 Series Coupé','420i'),
    ('BMW','425d','4 Series Coupé','425d'),
    ('BMW','428i','4 Series Coupé','428i'),
    ('BMW','430d','4 Series Coupé','430d'),
    ('BMW','430i','4 Series Coupé','430i'),
    ('BMW','435d','4 Series Coupé','435d'),
    ('BMW','435i','4 Series Coupé','435i'),
    ('BMW','440i','4 Series Coupé','440i'),
    ('BMW','M440d','4 Series Coupé','M440d'),
    ('BMW','M440i','4 Series Coupé','M440i'),
    ('BMW','518d','5 Series','518d'),
    ('BMW','520d','5 Series','520d'),
    ('BMW','520e','5 Series','520e'),
    ('BMW','520i','5 Series','520i'),
    ('BMW','523i','5 Series','523i'),
    ('BMW','525d','5 Series','525d'),
    ('BMW','528i','5 Series','528i'),
    ('BMW','530d','5 Series','530d'),
    ('BMW','530e','5 Series','530e'),
    ('BMW','530i','5 Series','530i'),
    ('BMW','535d','5 Series','535d'),
    ('BMW','535i','5 Series','535i'),
    ('BMW','540d','5 Series','540d'),
    ('BMW','540i','5 Series','540i'),
    ('BMW','545e','5 Series','545e'),
    ('BMW','550e','5 Series','550e'),
    ('BMW','550i','5 Series','550i'),
    ('BMW','M550d','5 Series','M550d'),
    ('BMW','M550i','5 Series','M550i'),
    ('BMW','620d','6 Series Gran Turismo','620d'),
    ('BMW','630d','6 Series Gran Turismo','630d'),
    ('BMW','630i','6 Series Gran Turismo','630i'),
    ('BMW','640d','6 Series Coupé','640d'),
    ('BMW','640i','6 Series Coupé','640i'),
    ('BMW','650i','6 Series Coupé','650i'),
    ('BMW','730d','7 Series','730d'),
    ('BMW','740d','7 Series','740d'),
    ('BMW','740e','7 Series','740e'),
    ('BMW','740i','7 Series','740i'),
    ('BMW','745e','7 Series','745e'),
    ('BMW','750d','7 Series','750d'),
    ('BMW','750i','7 Series','750i'),
    ('BMW','760i','7 Series','760i'),
    ('BMW','M760e','7 Series','M760e'),
    ('BMW','M760i','7 Series','M760i'),
    ('BMW','840d','8 Series Coupé','840d'),
    ('BMW','840i','8 Series Coupé','840i'),
    ('BMW','850i','8 Series Coupé','850i'),
    ('BMW','M850i','8 Series Coupé','M850i'),
    ('BMW','20 xDrive','X1','xDrive20d'),
    ('BMW','sDrive16d','X1','sDrive16d'),
    ('BMW','sDrive18d','X1','sDrive18d'),
    ('BMW','sDrive18i','X1','sDrive18i'),
    ('BMW','sDrive20d','X1','sDrive20d'),
    ('BMW','sDrive20i','X1','sDrive20i'),
    ('BMW','sDrive25d','X2','sDrive25d'),
    ('BMW','sDrive23i','Z4','sDrive23i'),
    ('BMW','sDrive28i','Z4','sDrive28i'),
    ('BMW','sDrive30i','Z4','sDrive30i'),
    ('BMW','sDrive35i','Z4','sDrive35i'),
    ('BMW','M35i','X1','M35i'),
    ('BMW','xDrive18d','X1','xDrive18d'),
    ('BMW','xDrive23i','X1','xDrive23i'),
    ('BMW','xDrive25e','X1','xDrive25e'),
    ('BMW','xDrive20d','X3','xDrive20d'),
    ('BMW','xDrive20i','X3','xDrive20i'),
    ('BMW','xDrive23d','X3','xDrive23d'),
    ('BMW','xDrive25d','X3','xDrive25d'),
    ('BMW','xDrive28i','X3','xDrive28i'),
    ('BMW','xDrive30e','X3','xDrive30e'),
    ('BMW','xDrive30i','X3','xDrive30i'),
    ('BMW','M40d','X3','M40d'),
    ('BMW','M40i','X3','M40i'),
    ('BMW','xDrive30d','X5','xDrive30d'),
    ('BMW','xDrive35d','X5','xDrive35d'),
    ('BMW','xDrive35i','X5','xDrive35i'),
    ('BMW','xDrive40d','X5','xDrive40d'),
    ('BMW','xDrive40e','X5','xDrive40e'),
    ('BMW','xDrive40i','X5','xDrive40i'),
    ('BMW','xDrive45e','X5','xDrive45e'),
    ('BMW','xDrive50e','X5','xDrive50e'),
    ('BMW','xDrive50i','X5','xDrive50i'),
    ('BMW','M50d','X5','M50d'),
    ('BMW','M50i','X5','M50i'),
    ('BMW','M60i','X5','M60i'),
    ('BMW','M50','i4','M50')
) as t(make, from_name, model, variant);

insert into public.variants (model_id, name, source)
select mo.id, r.variant, 'catalog_variants_v1'
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(r.model)
on conflict (model_id, normalized_name) do nothing;

insert into public.vehicle_aliases (entity_type, make_id, model_id, alias, normalized_alias, source)
select 'model', mk.id, mo.id, r.from_name, public.normalize_vehicle_name(r.from_name), 'catalog_variants_v1'
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(r.model)
where not exists (
  select 1 from public.vehicle_aliases va
  where va.entity_type = 'model' and va.make_id = mk.id
    and va.normalized_alias = public.normalize_vehicle_name(r.from_name));

update public.listings l
set model_id = mo.id, variant_id = v.id
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
join public.models orphan on orphan.make_id = mk.id
 and orphan.normalized_name = public.normalize_vehicle_name(r.from_name)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(r.model)
join public.variants v on v.model_id = mo.id
 and v.normalized_name = public.normalize_vehicle_name(r.variant)
where l.model_id = orphan.id;

update public.models mo set is_active = false, updated_at = now()
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
where mo.make_id = mk.id
  and mo.normalized_name = public.normalize_vehicle_name(r.from_name);

commit;