-- Generated by src/scripts/import-variant-catalog.mjs — do not edit by hand.
begin;

-- ---------- models the CSV never carried ----------
with m(make, name) as (values
    ('BMW','2 Series Coupé'),
    ('BMW','2 Series Cabriolet'),
    ('BMW','2 Series Active Tourer'),
    ('BMW','2 Series Gran Tourer'),
    ('BMW','2 Series Gran Coupé'),
    ('BMW','3 Series Touring'),
    ('BMW','3 Series Gran Turismo'),
    ('BMW','4 Series Coupé'),
    ('BMW','4 Series Cabriolet'),
    ('BMW','4 Series Gran Coupé'),
    ('BMW','5 Series Touring'),
    ('BMW','5 Series Gran Turismo'),
    ('BMW','6 Series Coupé'),
    ('BMW','6 Series Cabriolet'),
    ('BMW','6 Series Gran Coupé'),
    ('BMW','6 Series Gran Turismo'),
    ('BMW','7 Series'),
    ('BMW','8 Series Coupé'),
    ('BMW','8 Series Cabriolet'),
    ('BMW','8 Series Gran Coupé'),
    ('Mercedes','A-Class'),
    ('Mercedes','B-Class'),
    ('Mercedes','CLA'),
    ('Mercedes','CLS'),
    ('Mercedes','G-Class'),
    ('Mercedes','GLA'),
    ('Mercedes','GLB'),
    ('Mercedes','GLS'),
    ('Mercedes','V-Class'),
    ('Mercedes','Maybach S-Class'),
    ('Mini','Hatch 5-Türer'),
    ('Opel','Astra'),
    ('Opel','Corsa'),
    ('Opel','Insignia'),
    ('Opel','Zafira Tourer'),
    ('Vauxhall','Astra'),
    ('Vauxhall','Corsa'),
    ('Vauxhall','Insignia'),
    ('Vauxhall','Zafira')
)
insert into public.models (make_id, name, source)
select mk.id, m.name, 'catalog_variants_v1'
from m
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(m.make)
on conflict (make_id, normalized_name) do nothing;

-- ---------- variants ----------
with g(make, models, variants) as (values
    ('Audi',array['A1','A1 Sportback'],array['1.0 TFSI','1.2 TFSI','1.4 TFSI','1.6 TDI','2.0 TDI','25 TFSI','30 TFSI','35 TFSI','40 TFSI']),
    ('Audi',array['A1 allstreet / citycarver'],array['25 TFSI','30 TFSI','35 TFSI']),
    ('Audi',array['A3','A3 Sportback'],array['1.0 TFSI','1.2 TFSI','1.4 TFSI','1.5 TFSI','1.6 TDI','1.8 TFSI','1.8 TFSI quattro','2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','30 TDI','30 TFSI','35 TDI','35 TFSI','40 TDI quattro','40 TFSI quattro']),
    ('Audi',array['A3 Limousine'],array['1.0 TFSI','1.4 TFSI','1.5 TFSI','1.6 TDI','1.8 TFSI quattro','2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','30 TDI','30 TFSI','35 TDI','35 TFSI','40 TDI quattro','40 TFSI quattro']),
    ('Audi',array['A3 Cabriolet'],array['1.4 TFSI','1.8 TFSI','1.8 TFSI quattro','2.0 TDI','2.0 TFSI quattro','30 TFSI','35 TFSI']),
    ('Audi',array['A3 allstreet'],array['30 TDI','30 TFSI','35 TDI','35 TFSI']),
    ('Audi',array['A3 allstreet'],array['40 TFSI e']),
    ('Audi',array['A3 Sportback'],array['40 TFSI e','45 TFSI e']),
    ('Audi',array['A4','A4 Avant'],array['1.4 TFSI','1.8 TFSI','2.0 TDI','2.0 TDI quattro','2.0 TFSI','2.0 TFSI quattro','3.0 TDI (V6)','3.0 TDI quattro','30 TDI','35 TDI','35 TFSI','40 TDI','40 TDI quattro','40 TFSI','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['A4 allroad'],array['2.0 TDI quattro','2.0 TFSI quattro','3.0 TDI quattro','40 TDI quattro','45 TFSI quattro']),
    ('Audi',array['A5','A5 Sportback'],array['1.8 TFSI','2.0 TDI','2.0 TDI quattro','2.0 TFSI','2.0 TFSI quattro','3.0 TDI quattro','35 TDI','35 TFSI','40 TDI quattro','40 TFSI','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['A5 Cabriolet'],array['1.8 TFSI','2.0 TDI','2.0 TFSI quattro','3.0 TDI quattro','35 TFSI','40 TFSI','45 TFSI quattro']),
    ('Audi',array['A5 Avant','A5 Limousine'],array['35 TDI','35 TFSI','40 TDI quattro','40 TFSI','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['A6','A6 Avant'],array['2.0 TDI','2.0 TFSI','3.0 TDI (V6)','3.0 TDI quattro','3.0 TFSI quattro','35 TDI','40 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI quattro','55 TFSI e quattro']),
    ('Audi',array['A6 Limousine'],array['35 TDI','40 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI quattro']),
    ('Audi',array['A6 allroad'],array['3.0 TDI quattro','45 TDI quattro','50 TDI quattro','55 TDI quattro']),
    ('Audi',array['A5 Avant','A5 Limousine','A6 Avant','A6 Limousine','Q5','Q5 Sportback'],array['e-hybrid 299 PS','e-hybrid 367 PS']),
    ('Audi',array['A6 e-tron','A6 Avant e-tron','A6 Sportback e-tron','Q6 e-tron','Q6 Sportback e-tron','Q6 SUV e-tron'],array['performance','quattro']),
    ('Audi',array['A7'],array['3.0 TDI quattro','3.0 TFSI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI quattro','55 TFSI e quattro']),
    ('Audi',array['A8'],array['3.0 TDI quattro','4.0 TFSI quattro','50 TDI quattro','55 TFSI quattro','60 TFSI e quattro','L 50 TDI quattro','L 55 TFSI quattro','L 60 TFSI e quattro']),
    ('Audi',array['Q2'],array['1.0 TFSI','1.4 TFSI','1.6 TDI','2.0 TDI quattro','30 TDI','30 TFSI','35 TDI quattro','35 TFSI']),
    ('Audi',array['Q3'],array['1.4 TFSI','2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','35 TDI','35 TDI quattro','35 TFSI','40 TDI quattro','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['Q3 Sportback'],array['35 TDI','35 TDI quattro','35 TFSI','40 TDI quattro','40 TFSI quattro','45 TFSI quattro']),
    ('Audi',array['Q3','Q3 Sportback'],array['45 TFSI e']),
    ('Audi',array['Q4 e-tron','Q4 Sportback e-tron'],array['35 e-tron','40 e-tron','45 e-tron','45 e-tron quattro','50 e-tron quattro','55 e-tron quattro']),
    ('Audi',array['Q5'],array['2.0 TDI','2.0 TDI quattro','2.0 TFSI quattro','3.0 TDI quattro','35 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI e quattro']),
    ('Audi',array['Q5 Sportback'],array['35 TDI','40 TDI quattro','45 TFSI quattro','50 TDI quattro','55 TFSI e quattro']),
    ('Audi',array['Q7'],array['3.0 TDI quattro','3.0 TFSI quattro','45 TDI quattro','50 TDI quattro','55 TFSI quattro','60 TFSI e quattro']),
    ('Audi',array['Q8'],array['45 TDI quattro','50 TDI quattro','55 TFSI quattro','60 TFSI e quattro']),
    ('Audi',array['Q8 e-tron','Q8 Sportback e-tron','e-tron','e-tron Sportback'],array['50 quattro','55 quattro']),
    ('Audi',array['e-tron S','e-tron S Sportback','SQ8 e-tron','SQ8 Sportback e-tron'],array['503 PS']),
    ('Audi',array['e-tron GT'],array['quattro','performance quattro']),
    ('Audi',array['S e-tron GT'],array['679 PS']),
    ('Audi',array['RS e-tron GT'],array['598 PS','performance']),
    ('Audi',array['R8'],array['V10','V10 plus','V10 performance quattro','V10 RWD','V10 Spyder','GT RWD']),
    ('Audi',array['TT'],array['1.8 TFSI','2.0 TDI ultra','2.0 TFSI','2.0 TFSI quattro','40 TFSI','45 TFSI quattro']),
    ('Audi',array['TTS','S1','S3','S3 Sportback','S3 Limousine','SQ2','SQ3'],array['2.0 TFSI quattro']),
    ('Audi',array['TT RS','RS3','RS 3 Sportback','RS 3 Limousine','RSQ3','RS Q3 Sportback'],array['2.5 TFSI quattro']),
    ('Audi',array['S4','S5','S5 Avant','S5 Limousine','SQ5'],array['3.0 TDI quattro','3.0 TFSI quattro']),
    ('Audi',array['SQ5 Sportback'],array['3.0 TDI quattro']),
    ('Audi',array['S6','S7'],array['3.0 TDI quattro','4.0 TFSI quattro']),
    ('Audi',array['S8'],array['4.0 TFSI quattro']),
    ('Audi',array['S6 Avant e-tron','S6 Sportback e-tron'],array['551 PS']),
    ('Audi',array['SQ6 Sportback e-tron','SQ6 SUV e-tron'],array['489 PS']),
    ('Audi',array['SQ7','SQ8'],array['4.0 TDI quattro','4.0 TFSI quattro']),
    ('Audi',array['RS4','RS5'],array['2.9 TFSI quattro','4.2 FSI quattro']),
    ('Audi',array['RS 5 Sportback'],array['2.9 TFSI quattro']),
    ('Audi',array['RS6','RS7','RSQ8'],array['4.0 TFSI quattro','4.0 TFSI quattro performance']),
    ('BMW',array['1 Series'],array['114d','114i','116','116d','116i','118d','118i','120','120d','120i','123d','125d','125i','128ti','135i','M135','M135i','M140i']),
    ('BMW',array['2 Series Coupé'],array['218d','218i','220','220d','220i','225d','228i','230i','M235','M235i','M240i']),
    ('BMW',array['2 Series Cabriolet'],array['218d','218i','220d','220i','228i','230i','M235i','M240i']),
    ('BMW',array['2 Series Active Tourer'],array['214d','216d','216i','218d','218i','220d','220i','223d','223i','225e','225i','225xe','230e']),
    ('BMW',array['2 Series Gran Tourer'],array['214d','216d','216i','218d','218i','220d','220i']),
    ('BMW',array['2 Series Gran Coupé'],array['216d','218d','218i','220d','220i','228i','M235i']),
    ('BMW',array['3 Series'],array['316d','316i','318d','318i','320d','320e','320i','325d','325i','328i','330d','330e','330i','335d','335i','340i','M340d','M340i']),
    ('BMW',array['3 Series Touring'],array['316d','316i','318d','318i','320d','320e','320i','325d','328i','330d','330e','330i','335d','335i','340i','M340d','M340i']),
    ('BMW',array['3 Series Gran Turismo'],array['318d','320d','320i','325d','328i','330d','330i','335d','335i','340i']),
    ('BMW',array['4 Series Coupé','4 Series Gran Coupé'],array['418d','418i','420d','420i','425d','428i','430d','430i','435d','435i','440i','M440d','M440i']),
    ('BMW',array['4 Series Cabriolet'],array['420d','420i','428i','430d','430i','435i','440i','M440i']),
    ('BMW',array['5 Series'],array['518d','520d','520e','520i','523i','525d','528i','530d','530e','530i','535d','535i','540d','540i','545e','550e','550i','M550d','M550i'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('BMW',array['5 Series Touring'],array['518d','520d','520i','525d','530d','530e','530i','535d','535i','540d','540i','M550d']),
    ('BMW',array['5 Series Gran Turismo'],array['520d','530d','535d','535i','550i']),
    ('BMW',array['6 Series Coupé','6 Series Cabriolet','6 Series Gran Coupé'],array['640d','640i','650i']),
    ('BMW',array['6 Series Gran Turismo'],array['620d','630d','630i','640d','640i']),
    ('BMW',array['7 Series'],array['730d','730i','740d','740e','740i','745e','750d','750e','750i','760i','M760e','M760i']),
    ('BMW',array['8 Series Coupé'],array['840d','840i','850i','M850i']),
    ('BMW',array['8 Series Cabriolet','8 Series Gran Coupé'],array['840d','840i','M850i']),
    ('BMW',array['X1'],array['sDrive16d','sDrive18d','sDrive18i','sDrive20d','sDrive20i','xDrive18d','xDrive20d','xDrive20i','xDrive23i','xDrive25d','xDrive25e','xDrive25i','xDrive28i','xDrive30e','M35i']),
    ('BMW',array['X2'],array['sDrive18d','sDrive18i','sDrive20i','sDrive25d','xDrive18d','xDrive20d','xDrive20i','xDrive25d','xDrive25e','M35i']),
    ('BMW',array['X3'],array['sDrive18d','sDrive20i','xDrive20d','xDrive20i','xDrive23d','xDrive25d','xDrive28i','xDrive30d','xDrive30e','xDrive30i','xDrive35d','xDrive35i','M40d','M40i']),
    ('BMW',array['X4'],array['xDrive20d','xDrive20i','xDrive28i','xDrive30d','xDrive30i','xDrive35d','xDrive35i','M40d','M40i']),
    ('BMW',array['X5'],array['sDrive25d','xDrive25d','xDrive30d','xDrive35i','xDrive40d','xDrive40e','xDrive40i','xDrive45e','xDrive50e','xDrive50i','M50d','M50i','M60i']),
    ('BMW',array['X6'],array['xDrive30d','xDrive35i','xDrive40d','xDrive40i','xDrive50i','M50d','M50i','M60i']),
    ('BMW',array['X7'],array['xDrive30d','xDrive40d','xDrive40i','M50d','M50i','M60i']),
    ('BMW',array['Z4'],array['sDrive18i','sDrive20i','sDrive23i','sDrive28i','sDrive30i','sDrive35i','M40i']),
    ('BMW',array['i3'],array['60 Ah','94 Ah','120 Ah']),
    ('BMW',array['i3s'],array['94 Ah','120 Ah']),
    ('BMW',array['i4'],array['eDrive35','eDrive40','xDrive40','M50']),
    ('BMW',array['i5','i5 Touring'],array['eDrive40','xDrive40','M60']),
    ('BMW',array['i7'],array['eDrive50','xDrive60','M70']),
    ('BMW',array['i8'],array['Coupé','Roadster']),
    ('BMW',array['iX'],array['xDrive40','xDrive50','M60']),
    ('BMW',array['iX1','iX2'],array['eDrive20','xDrive30']),
    ('BMW',array['iX3'],array['eDrive20','xDrive50','80 kWh']),
    ('BMW',array['M2'],array['3.0','Competition','CS']),
    ('BMW',array['M3'],array['3.0','Competition','Competition xDrive','CS']),
    ('BMW',array['M3 Touring'],array['Competition xDrive']),
    ('BMW',array['M4'],array['3.0','Competition','Competition xDrive','CS','CSL']),
    ('BMW',array['M5'],array['4.4 V8','Competition','CS']),
    ('BMW',array['M5 Touring'],array['4.4 V8']),
    ('BMW',array['M6'],array['4.4 V8','Competition','Gran Coupé']),
    ('BMW',array['M8'],array['Competition','Gran Coupé','Competition Gran Coupé']),
    ('BMW',array['X3 M','X4 M','X5 M','X6 M'],array['Competition']),
    ('BMW',array['XM'],array['653 PS']),
    ('BMW',array['XM 50e'],array['476 PS']),
    ('BMW',array['XM Label'],array['748 PS']),
    ('BMW',array['1M Coupé'],array['3.0']),
    ('BMW',array['ActiveHybrid 3','ActiveHybrid 5'],array['3.0']),
    ('BMW',array['ActiveHybrid 7','ActiveHybrid X6'],array['4.4 V8']),
    ('Ford',array['B-MAX'],array['1.0 EcoBoost','1.4 Duratec','1.5 TDCi','1.6 TDCi']),
    ('Ford',array['C-MAX','Grand C-MAX'],array['1.0 EcoBoost','1.5 EcoBoost','1.6 TDCi','1.5 TDCi','2.0 TDCi']),
    ('Ford',array['EcoSport'],array['1.0 EcoBoost','1.5 Ti-VCT','1.5 TDCi']),
    ('Ford',array['Edge','Edge L'],array['2.0 TDCi','2.0 EcoBlue','2.7 EcoBoost V6']),
    ('Ford',array['Fiesta'],array['1.0 EcoBoost','1.1 Ti-VCT','1.25 Duratec','1.5 TDCi','1.6 TDCi']),
    ('Ford',array['Fiesta ST'],array['1.5 EcoBoost','1.6 EcoBoost']),
    ('Ford',array['Focus'],array['1.0 EcoBoost','1.5 EcoBoost','1.6 TDCi','1.5 EcoBlue','2.0 EcoBlue','2.0 TDCi']),
    ('Ford',array['Focus ST'],array['2.0 EcoBoost','2.3 EcoBoost','2.0 EcoBlue']),
    ('Ford',array['Focus RS'],array['2.3 EcoBoost']),
    ('Ford',array['Fusion'],array['1.4 Duratec','1.6 Duratec','1.6 TDCi']),
    ('Ford',array['Galaxy','S-MAX'],array['1.5 EcoBoost','2.0 EcoBoost','2.0 TDCi','2.0 EcoBlue']),
    ('Ford',array['Ka'],array['1.2 Duratec','1.0 Ti-VCT','1.5 TDCi']),
    ('Ford',array['Kuga'],array['1.5 EcoBoost','2.0 EcoBoost','2.0 TDCi','2.0 EcoBlue','2.5 Duratec PHEV']),
    ('Ford',array['Mondeo'],array['1.5 EcoBoost','2.0 EcoBoost','2.0 TDCi','2.0 EcoBlue','2.0 Hybrid']),
    ('Ford',array['Mustang'],array['2.3 EcoBoost','5.0 V8 GT','5.2 V8 Shelby GT350']),
    ('Ford',array['Puma'],array['1.0 EcoBoost','1.5 EcoBlue']),
    ('Ford',array['Puma ST'],array['1.0 EcoBoost','1.5 EcoBoost']),
    ('Ford',array['Ranger'],array['2.0 EcoBlue','2.2 TDCi','3.2 TDCi','3.0 V6 EcoBlue']),
    ('Ford',array['Ranger Raptor'],array['2.0 EcoBlue Bi-Turbo','3.0 EcoBoost V6']),
    ('Ford',array['Bronco'],array['2.3 EcoBoost','2.7 EcoBoost V6']),
    ('Ford',array['GT'],array['3.5 EcoBoost V6'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('Ford',array['Transit','Transit Connect'],array['1.5 EcoBlue','2.0 EcoBlue','2.2 TDCi','1.6 TDCi']),
    ('Ford',array['Transit Custom','Tourneo Custom'],array['2.0 EcoBlue','2.2 TDCi','2.5 Duratec PHEV']),
    ('Ford',array['Transit Courier','Tourneo Courier'],array['1.0 EcoBoost','1.5 EcoBlue','1.5 TDCi']),
    ('Ford',array['Tourneo Connect','Grand Tourneo Connect'],array['1.5 EcoBoost','1.5 EcoBlue','2.0 TDCi']),
    ('Ford',array['Mustang Mach-E'],array['70 kWh','91 kWh','70 kWh AWD','91 kWh AWD','GT']),
    ('Ford',array['Capri','Capri EV'],array['52 kWh','77 kWh','79 kWh AWD']),
    ('Ford',array['Explorer'],array['3.0 EcoBoost PHEV','52 kWh','77 kWh','79 kWh AWD']),
    ('Ford',array['Puma Gen-E'],array['43 kWh']),
    ('Ford',array['F-150 Lightning'],array['98 kWh','131 kWh']),
    ('Ford',array['E-Transit'],array['68 kWh','89 kWh']),
    ('Ford',array['E-Transit Custom','E-Tourneo Custom'],array['64 kWh','74 kWh']),
    ('Ford',array['E-Transit Courier','E-Tourneo Courier'],array['43 kWh']),
    ('Hyundai',array['Ioniq 5','Ioniq 6'],array['58 kWh','63 kWh','77.4 kWh','84 kWh','77.4 kWh AWD','84 kWh AWD']),
    ('Hyundai',array['Ioniq 9'],array['110 kWh','110 kWh AWD']),
    ('Hyundai',array['Ioniq'],array['1.6 GDI Hybrid','1.6 GDI Plug-in','38.3 kWh']),
    ('Hyundai',array['Ioniq 5 N','Ioniq 6 N'],array['84 kWh N']),
    ('Hyundai',array['i10'],array['1.0','1.2','1.0 T-GDi']),
    ('Hyundai',array['i20','i20 Coupé'],array['1.0 T-GDi','1.2 MPi','1.4','1.4 CRDi']),
    ('Hyundai',array['i20 N'],array['1.6 T-GDi']),
    ('Hyundai',array['i30','i30 Fastback'],array['1.0 T-GDi','1.4 T-GDi','1.5 T-GDi','1.6 GDi','1.6 CRDi']),
    ('Hyundai',array['i30 N','i30 N Fastback'],array['2.0 T-GDi']),
    ('Hyundai',array['i40'],array['1.6 GDi','2.0 GDi','1.7 CRDi']),
    ('Hyundai',array['Accent'],array['1.4','1.6','1.6 CRDi']),
    ('Hyundai',array['Elantra'],array['1.6','2.0','1.6 CRDi']),
    ('Hyundai',array['Matrix'],array['1.6','1.8','1.5 CRDi']),
    ('Hyundai',array['Sonata'],array['2.0','2.4','1.6 T-GDi','2.0 Hybrid']),
    ('Hyundai',array['Veloster'],array['1.6 GDi','1.6 T-GDi']),
    ('Hyundai',array['Genesis'],array['3.8 V6','5.0 V8']),
    ('Hyundai',array['Genesis Coupé'],array['2.0 T','3.8 V6']),
    ('Hyundai',array['Equus'],array['3.8 V6','4.6 V8']),
    ('Hyundai',array['Bayon'],array['1.0 T-GDi','1.2 MPi']),
    ('Hyundai',array['Kona'],array['1.0 T-GDi','1.6 T-GDi','1.6 CRDi','1.6 GDi Hybrid','39 kWh','64 kWh','65 kWh']),
    ('Hyundai',array['Kona N'],array['2.0 T-GDi']),
    ('Hyundai',array['ix20'],array['1.4','1.6','1.4 CRDi','1.6 CRDi']),
    ('Hyundai',array['ix25'],array['1.6','2.0']),
    ('Hyundai',array['ix35'],array['1.6 GDi','2.0','1.7 CRDi','2.0 CRDi']),
    ('Hyundai',array['ix55'],array['3.0 V6 CRDi']),
    ('Hyundai',array['Tucson'],array['1.6 T-GDi','1.6 CRDi','2.0 CRDi','1.6 T-GDi Hybrid','1.6 T-GDi PHEV']),
    ('Hyundai',array['Santa Fe'],array['2.2 CRDi','2.4 GDi','1.6 T-GDi Hybrid','1.6 T-GDi PHEV']),
    ('Hyundai',array['Grand Santa Fe'],array['2.2 CRDi','3.3 V6']),
    ('Hyundai',array['Staria'],array['2.2 CRDi','3.5 V6']),
    ('Hyundai',array['H-1 Cargo','H-1 Travel'],array['2.5 CRDi']),
    ('Hyundai',array['H350'],array['2.5 CRDi']),
    ('Hyundai',array['Inster'],array['42 kWh','49 kWh']),
    ('Hyundai',array['Nexo'],array['Fuel Cell']),
    ('Kia',array['Picanto'],array['1.0','1.2','1.0 T-GDi']),
    ('Kia',array['Rio'],array['1.0 T-GDi','1.2','1.4','1.4 CRDi']),
    ('Kia',array['Venga'],array['1.4','1.6','1.4 CRDi','1.6 CRDi']),
    ('Kia',array['Stonic'],array['1.0 T-GDi','1.2','1.4','1.6 CRDi']),
    ('Kia',array['Cee''d','Cee''d SW'],array['1.4','1.6 GDi','1.4 CRDi','1.6 CRDi']),
    ('Kia',array['Ceed Sportswagon','ProCeed','XCeed'],array['1.0 T-GDi','1.4 T-GDi','1.5 T-GDi','1.6 CRDi','1.6 T-GDi PHEV']),
    ('Kia',array['Ceed GT','ProCeed GT'],array['1.6 T-GDi']),
    ('Kia',array['Carens'],array['1.6 GDi','1.7 CRDi','2.0']),
    ('Kia',array['Carnival'],array['2.2 CRDi','3.3 V6','1.6 T-GDi Hybrid']),
    ('Kia',array['Magentis'],array['2.0','2.7 V6','2.0 CRDi']),
    ('Kia',array['Optima','Optima Sportswagon'],array['1.6 T-GDi','2.0','1.7 CRDi','2.0 PHEV']),
    ('Kia',array['Forte','K4'],array['1.6','2.0','1.6 T-GDi']),
    ('Kia',array['Quoris'],array['3.8 V6','5.0 V8']),
    ('Kia',array['Niro'],array['1.6 GDi Hybrid','1.6 GDi PHEV']),
    ('Kia',array['Soul'],array['1.6 GDi','1.6 CRDi'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('Kia',array['Sorento'],array['2.2 CRDi','2.4 GDi','1.6 T-GDi Hybrid','1.6 T-GDi PHEV']),
    ('Kia',array['Sportage'],array['1.6 T-GDi','1.6 CRDi','2.0 CRDi','1.6 T-GDi Hybrid','1.6 T-GDi PHEV']),
    ('Kia',array['Stinger'],array['2.0 T-GDi','3.3 T-GDi V6','2.2 CRDi']),
    ('Kia',array['e-Niro','e-Soul'],array['39 kWh','64 kWh']),
    ('Kia',array['EV2'],array['42 kWh','51 kWh']),
    ('Kia',array['EV3'],array['58 kWh','81 kWh']),
    ('Kia',array['EV4','EV4 Fastback','EV4 Hatchback'],array['58 kWh','81 kWh']),
    ('Kia',array['EV5'],array['64 kWh','88 kWh']),
    ('Kia',array['EV6'],array['58 kWh','77 kWh','84 kWh','77 kWh AWD']),
    ('Kia',array['EV6 GT'],array['77 kWh GT','84 kWh GT']),
    ('Kia',array['EV9'],array['76 kWh','99 kWh','99 kWh AWD']),
    ('Kia',array['EV9 GT'],array['99 kWh GT']),
    ('Kia',array['PV5','PV5 Cargo','PV5 Chassis Cab','PV5 Passenger'],array['51 kWh','71 kWh']),
    ('Mercedes',array['AMG A 35'],array['A 35 4MATIC']),
    ('Mercedes',array['AMG A 45'],array['A 45 4MATIC+','A 45 S 4MATIC+']),
    ('Mercedes',array['AMG C 43'],array['C 43 4MATIC']),
    ('Mercedes',array['AMG C 63'],array['C 63 4MATIC+','C 63 S','C 63 S E Performance']),
    ('Mercedes',array['AMG CLA 35'],array['CLA 35 4MATIC']),
    ('Mercedes',array['AMG CLA 45'],array['CLA 45 4MATIC+','CLA 45 S 4MATIC+']),
    ('Mercedes',array['AMG E 53'],array['E 53 4MATIC+','E 53 Hybrid 4MATIC+']),
    ('Mercedes',array['AMG E 63'],array['E 63 4MATIC+','E 63 S 4MATIC+']),
    ('Mercedes',array['AMG G 63'],array['G 63 4MATIC']),
    ('Mercedes',array['AMG GLC 43'],array['GLC 43 4MATIC']),
    ('Mercedes',array['AMG GLC 63'],array['GLC 63 4MATIC+','GLC 63 S 4MATIC+','GLC 63 S E Performance']),
    ('Mercedes',array['AMG GLE 53'],array['GLE 53 4MATIC+']),
    ('Mercedes',array['AMG GLE 63'],array['GLE 63 4MATIC+','GLE 63 S 4MATIC+']),
    ('Mercedes',array['EQA'],array['EQA 250','EQA 250+ (Long Range)','EQA 300 4MATIC','EQA 350 4MATIC']),
    ('Mercedes',array['EQB'],array['EQB 250','EQB 250+ (Long Range)','EQB 300 4MATIC','EQB 350 4MATIC']),
    ('Mercedes',array['EQC'],array['EQC 400 4MATIC']),
    ('Mercedes',array['EQE'],array['EQE 300','EQE 350','EQE 350 4MATIC','EQE 500 4MATIC']),
    ('Mercedes',array['EQE SUV'],array['EQE 350+','EQE 350 4MATIC','EQE 500 4MATIC']),
    ('Mercedes',array['EQS'],array['EQS 450+','EQS 450 4MATIC','EQS 500 4MATIC','EQS 580 4MATIC']),
    ('Mercedes',array['EQS SUV'],array['EQS 450+','EQS 450 4MATIC','EQS 580 4MATIC']),
    ('Mercedes',array['EQV'],array['EQV 250','EQV 300']),
    ('Mercedes',array['Vito','eVito'],array['110 CDI','114 CDI','116 CDI','119 CDI','124 CDI']),
    ('Mercedes',array['Sprinter','eSprinter'],array['211 CDI','214 CDI','216 CDI','311 CDI','314 CDI','316 CDI','319 CDI','516 CDI']),
    ('Mercedes',array['Citan','eCitan'],array['108 CDI','109 CDI','110 CDI','112','113']),
    ('Mercedes',array['Marco Polo'],array['220 d','250 d','300 d']),
    ('Mercedes',array['X-Class'],array['X 220 d','X 250 d','X 350 d 4MATIC']),
    ('Mercedes',array['T-Class'],array['T 160','T 180','T 180 d','T 200']),
    ('Mercedes',array['AMG CLS 53'],array['CLS 53 4MATIC+']),
    ('Mercedes',array['AMG CLS 63'],array['CLS 63 4MATIC','CLS 63 S 4MATIC+']),
    ('Mercedes',array['AMG E 43'],array['E 43 4MATIC']),
    ('Mercedes',array['AMG EQE 43'],array['EQE 43 4MATIC']),
    ('Mercedes',array['AMG EQE 53'],array['EQE 53 4MATIC+']),
    ('Mercedes',array['AMG EQS 53'],array['EQS 53 4MATIC+']),
    ('Mercedes',array['AMG G 65'],array['G 65']),
    ('Mercedes',array['AMG GLA 35'],array['GLA 35 4MATIC']),
    ('Mercedes',array['AMG GLA 45'],array['GLA 45 4MATIC+','GLA 45 S 4MATIC+']),
    ('Mercedes',array['AMG GLB 35'],array['GLB 35 4MATIC']),
    ('Mercedes',array['AMG GLE 43'],array['GLE 43 4MATIC']),
    ('Mercedes',array['AMG GLS 63'],array['GLS 63 4MATIC+']),
    ('Mercedes',array['AMG S 63'],array['S 63 4MATIC+','S 63 E Performance']),
    ('Mercedes',array['AMG S 65'],array['S 65']),
    ('Mercedes',array['AMG SL 43'],array['SL 43']),
    ('Mercedes',array['AMG SL 55'],array['SL 55 4MATIC+']),
    ('Mercedes',array['AMG SLC 43'],array['SLC 43']),
    ('Mercedes',array['AMG ONE'],array['1.6 V6 Hybrid']),
    ('Mercedes',array['AMG GT 4-Door Coupé'],array['GT 43 4MATIC+','GT 53 4MATIC+','GT 63 4MATIC+','GT 63 S 4MATIC+']),
    ('Mercedes',array['Mercedes-AMG GT Coupé'],array['GT','GT S','GT C','GT R','GT Black Series'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('Mercedes',array['SL 63 AMG'],array['SL 63']),
    ('Mercedes',array['SL 65 AMG'],array['SL 65']),
    ('Mercedes',array['SLS AMG'],array['6.3 V8','6.3 V8 Black Series']),
    ('Mercedes',array['C-Klasse T-Modell'],array['C 180','C 200','C 220 d','C 250','C 300','C 300 de','C 300 e','C 350 e','C 400']),
    ('Mercedes',array['C-Klasse T-Modell All-Terrain'],array['C 200 4MATIC','C 220 d 4MATIC']),
    ('Mercedes',array['E-Klasse T-Modell'],array['E 200','E 220 d','E 250','E 300','E 300 de','E 300 e','E 350','E 400','E 450','E 500']),
    ('Mercedes',array['E-Klasse T-Modell All-Terrain'],array['E 220 d 4MATIC','E 400 d 4MATIC']),
    ('Mercedes',array['CLA Shooting Brake'],array['CLA 180','CLA 200','CLA 220','CLA 250','CLA 250 e']),
    ('Mercedes',array['CLS Shooting Brake'],array['CLS 250 d','CLS 350','CLS 400','CLS 500']),
    ('Mercedes',array['GLC Coupé'],array['GLC 200','GLC 220 d','GLC 250','GLC 300','GLC 300 de','GLC 300 e','GLC 400 d']),
    ('Mercedes',array['GLE Coupé'],array['GLE 350 d','GLE 400','GLE 400 d','GLE 450','GLE 500']),
    ('Mercedes',array['GLK'],array['GLK 200 CDI','GLK 220 CDI','GLK 250','GLK 300','GLK 350']),
    ('Mercedes',array['GL'],array['GL 350 BlueTEC','GL 400','GL 500','GL 63 AMG']),
    ('Mercedes',array['ML'],array['ML 250 CDI','ML 350','ML 350 BlueTEC','ML 500','ML 63 AMG']),
    ('Mercedes',array['R-Klasse'],array['R 280 CDI','R 300 CDI','R 350','R 500']),
    ('Mercedes',array['CL'],array['CL 500','CL 600','CL 63 AMG','CL 65 AMG']),
    ('Mercedes',array['CLC'],array['CLC 160','CLC 180','CLC 200 CDI','CLC 220 CDI']),
    ('Mercedes',array['SLK'],array['SLK 200','SLK 250','SLK 350','SLK 55 AMG']),
    ('Mercedes',array['Viano'],array['2.0 CDI','2.2 CDI','3.0 CDI','3.5']),
    ('Mercedes',array['EQT'],array['EQT 200','EQT 300']),
    ('Mercedes',array['Maybach GLS 600'],array['GLS 600 4MATIC']),
    ('Mercedes',array['Maybach EQS 680 SUV'],array['EQS 680 4MATIC']),
    ('Mini',array['Hatch','Hatch 5-Türer'],array['One D','Cooper D','Cooper SD']),
    ('Mini',array['Cabrio'],array['One','Cooper','Cooper D']),
    ('Mini',array['Clubman'],array['One','One D','Cooper','Cooper D','Cooper SD']),
    ('Mini',array['Clubvan'],array['Cooper','Cooper D']),
    ('Mini',array['Countryman'],array['One','One D','Cooper','Cooper D','Cooper SD','Cooper SE ALL4']),
    ('Mini',array['Coupé','Roadster'],array['Cooper','Cooper SD']),
    ('Mini',array['Paceman'],array['Cooper','Cooper D','Cooper SD']),
    ('Mini',array['Aceman'],array['Cooper E','Cooper SE']),
    ('Mini',array['John Cooper Works GP'],array['2.0 Turbo (GP)']),
    ('Opel',array['Astra'],array['1.2 Turbo','1.4 Turbo','1.6 Turbo','1.5 Diesel','1.6 CDTI','1.7 CDTI']),
    ('Opel',array['Corsa'],array['1.2','1.2 Turbo','1.4','1.4 Turbo','1.3 CDTI','1.5 Diesel']),
    ('Opel',array['Insignia'],array['1.5 Turbo','1.6 CDTI','2.0 CDTI','2.0 Turbo 4x4','2.0 CDTI 4x4']),
    ('Opel',array['Zafira','Zafira Tourer'],array['1.4 Turbo','1.6 CDTI','1.8','2.0 CDTI']),
    ('Peugeot',array['107','108'],array['1.0 VTi','1.2 PureTech','1.4 HDi']),
    ('Peugeot',array['206+'],array['1.1','1.4','1.4 HDi']),
    ('Peugeot',array['207','207 CC','207 SW'],array['1.4','1.6 VTi','1.6 THP','1.4 HDi','1.6 HDi']),
    ('Peugeot',array['208'],array['1.0 VTi','1.2 PureTech','1.4 HDi','1.5 BlueHDi','1.6 HDi']),
    ('Peugeot',array['208 GTi'],array['1.6 THP 200','1.6 THP 208']),
    ('Peugeot',array['301'],array['1.2 VTi','1.6 VTi','1.6 HDi']),
    ('Peugeot',array['308','308 SW'],array['1.2 PureTech','1.6 THP','1.5 BlueHDi','1.6 BlueHDi','2.0 BlueHDi','1.6 Hybrid']),
    ('Peugeot',array['308 CC'],array['1.6 THP','2.0 HDi']),
    ('Peugeot',array['308 GTi'],array['1.6 THP 250','1.6 THP 270']),
    ('Peugeot',array['2008'],array['1.2 PureTech','1.6 VTi','1.5 BlueHDi','1.6 HDi']),
    ('Peugeot',array['3008'],array['1.2 PureTech','1.6 PureTech','1.5 BlueHDi','2.0 BlueHDi','1.6 HDi','1.6 Hybrid4']),
    ('Peugeot',array['4007','4008'],array['1.6 HDi','2.0 HDi','2.2 HDi']),
    ('Peugeot',array['407','407 SW'],array['1.8','2.0','1.6 HDi','2.0 HDi','2.7 V6 HDi']),
    ('Peugeot',array['408'],array['1.2 PureTech','1.2 Hybrid','1.6 Hybrid']),
    ('Peugeot',array['5008'],array['1.2 PureTech','1.6 THP','1.5 BlueHDi','2.0 BlueHDi','1.6 HDi']),
    ('Peugeot',array['508','508 SW'],array['1.2 PureTech','1.6 PureTech','1.5 BlueHDi','2.0 BlueHDi','1.6 HDi','1.6 Hybrid']),
    ('Peugeot',array['508 PSE'],array['1.6 Hybrid4 360']),
    ('Peugeot',array['508 RXH'],array['2.0 HDi Hybrid4']),
    ('Peugeot',array['607'],array['2.0','2.2 HDi','2.7 V6 HDi']),
    ('Peugeot',array['807'],array['2.0','2.0 HDi','2.2 HDi']),
    ('Peugeot',array['Bipper','Bipper Tepee'],array['1.3 HDi','1.4 HDi']),
    ('Peugeot',array['Boxer'],array['2.0 BlueHDi','2.2 HDi','3.0 HDi']),
    ('Peugeot',array['Expert','Expert Tepee'],array['1.6 HDi','1.6 BlueHDi','2.0 HDi','2.0 BlueHDi']),
    ('Peugeot',array['Partner','Partner Rapid','Partner Tepee'],array['1.2 PureTech','1.6 HDi','1.5 BlueHDi','1.6 BlueHDi']),
    ('Peugeot',array['Rifter'],array['1.2 PureTech','1.5 BlueHDi'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('Peugeot',array['Traveller'],array['1.6 BlueHDi','2.0 BlueHDi']),
    ('Peugeot',array['RCZ'],array['1.6 THP','2.0 HDi']),
    ('Peugeot',array['RCZ R'],array['1.6 THP 270']),
    ('Peugeot',array['iOn'],array['16 kWh']),
    ('Peugeot',array['E-208','E-2008'],array['50 kWh','51 kWh']),
    ('Peugeot',array['E-208 GTi'],array['54 kWh GTi']),
    ('Peugeot',array['E-308','E-308 SW','E-408'],array['54 kWh','58 kWh']),
    ('Peugeot',array['E-3008','E-5008'],array['73 kWh','97 kWh','73 kWh Dual Motor']),
    ('Peugeot',array['E-Partner','E-Rifter'],array['50 kWh','54 kWh']),
    ('Peugeot',array['E-Expert','E-Traveller'],array['50 kWh','75 kWh']),
    ('Peugeot',array['E-Boxer'],array['37 kWh','70 kWh','110 kWh']),
    ('Porsche',array['911 GT3'],array['4.0 (GT3)','4.0 (GT3 Touring)']),
    ('Porsche',array['911 GT3 RS'],array['4.0 (GT3 RS)']),
    ('Porsche',array['911 GT2 RS'],array['3.8 Turbo (GT2 RS)']),
    ('Porsche',array['911 Dakar'],array['3.0 Turbo 4GTS']),
    ('Porsche',array['911 S/T'],array['4.0 (S/T)']),
    ('Porsche',array['911 Speedster'],array['4.0 (Speedster)']),
    ('Porsche',array['911 Sport Classic'],array['3.7 Turbo (Sport Classic)']),
    ('Porsche',array['911 R'],array['4.0 (911 R)']),
    ('Porsche',array['718 Cayman GT4'],array['4.0 (GT4)']),
    ('Porsche',array['718 Cayman GT4 RS'],array['4.0 (GT4 RS)']),
    ('Porsche',array['718 Spyder'],array['4.0 (Spyder)']),
    ('Porsche',array['718 Spyder RS'],array['4.0 (Spyder RS)']),
    ('Porsche',array['Boxster'],array['2.7','2.9','3.2 S','3.4 S','3.4 GTS','3.8 Spyder']),
    ('Porsche',array['Cayman'],array['2.7','2.9','3.4 S','3.4 GTS','3.4 R','3.8 GT4']),
    ('Porsche',array['918 Spyder'],array['4.6 Hybrid']),
    ('Porsche',array['Cayenne Coupé'],array['3.0 V6','3.0 E-Hybrid','2.9 S','4.0 GTS','4.0 Turbo','4.0 Turbo GT','4.0 Turbo E-Hybrid']),
    ('Porsche',array['Cayenne Electric'],array['Electric']),
    ('Porsche',array['Panamera Sport Turismo'],array['3.0 V6','2.9 4','2.9 4 E-Hybrid','2.9 4S','4.0 GTS','4.0 Turbo','4.0 Turbo S E-Hybrid']),
    ('Porsche',array['Taycan Cross Turismo','Taycan Sport Turismo'],array['4','4S','GTS','Turbo','Turbo S']),
    ('Renault',array['Clio'],array['1.0 TCe','1.2 TCe','1.3 TCe','1.5 dCi','1.6 E-Tech Hybrid']),
    ('Renault',array['Mégane'],array['1.2 TCe','1.3 TCe','1.5 dCi','1.6 dCi','1.6 E-Tech Plug-in']),
    ('Renault',array['Twingo'],array['1.0 SCe','0.9 TCe','1.5 dCi']),
    ('Renault',array['Clio RS'],array['1.6 Turbo','2.0 16V','Trophy']),
    ('Renault',array['Megane RS'],array['1.8 Turbo','2.0 Turbo','Trophy','Trophy-R']),
    ('Renault',array['Megane GT'],array['1.6 TCe','1.6 dCi']),
    ('Renault',array['Twingo RS'],array['1.6 16V']),
    ('Renault',array['Captur'],array['1.0 TCe','1.3 TCe','1.2 TCe','1.5 dCi','1.6 E-Tech Hybrid']),
    ('Renault',array['Kadjar'],array['1.2 TCe','1.3 TCe','1.5 dCi','1.6 dCi']),
    ('Renault',array['Arkana'],array['1.3 TCe','1.6 E-Tech Hybrid']),
    ('Renault',array['Austral'],array['1.2 TCe','1.3 TCe','1.2 E-Tech Hybrid']),
    ('Renault',array['Rafale'],array['1.2 E-Tech Hybrid','1.8 E-Tech Hybrid']),
    ('Renault',array['Symbioz'],array['1.6 E-Tech Hybrid']),
    ('Renault',array['Scenic','Grand Scenic'],array['1.2 TCe','1.3 TCe','1.5 dCi','1.6 dCi']),
    ('Renault',array['Modus','Grand Modus'],array['1.2','1.6','1.5 dCi']),
    ('Renault',array['Espace','Grand Espace'],array['1.6 dCi','2.0 dCi','1.8 TCe','1.2 E-Tech Hybrid']),
    ('Renault',array['Laguna'],array['1.5 dCi','2.0 dCi','2.0 TCe']),
    ('Renault',array['Latitude'],array['2.0 dCi','3.0 V6 dCi']),
    ('Renault',array['Talisman'],array['1.6 TCe','1.6 dCi','2.0 dCi']),
    ('Renault',array['Fluence'],array['1.6','2.0','1.5 dCi']),
    ('Renault',array['Symbol','Taliant'],array['1.0 TCe','1.2','1.6','1.5 dCi']),
    ('Renault',array['Koleos'],array['1.6 dCi','2.0 dCi','2.5']),
    ('Renault',array['Kaptur'],array['1.6','2.0']),
    ('Renault',array['Kardian'],array['1.0 TCe','1.6 SCe']),
    ('Renault',array['Duster Oroch','Oroch'],array['1.6','2.0']),
    ('Renault',array['Alaskan'],array['2.3 dCi']),
    ('Renault',array['Wind'],array['1.2 TCe','1.6']),
    ('Renault',array['Kangoo','Grand Kangoo'],array['1.3 TCe','1.5 dCi','1.6','45 kWh']),
    ('Renault',array['Express'],array['1.3 TCe','1.5 dCi']),
    ('Renault',array['Trafic','Trafic Combi','Trafic SpaceClass'],array['1.6 dCi','2.0 dCi','2.0 Blue dCi'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('Renault',array['Master'],array['2.3 dCi','2.3 Blue dCi','87 kWh']),
    ('Renault',array['ZOE'],array['22 kWh','41 kWh','52 kWh']),
    ('Renault',array['Twizy'],array['6.1 kWh']),
    ('Renault',array['4 E-Tech','5 E-Tech'],array['40 kWh','52 kWh']),
    ('Renault',array['Mégane E-Tech Electric'],array['40 kWh','60 kWh']),
    ('Renault',array['Scenic E-Tech Electric'],array['60 kWh','87 kWh']),
    ('Toyota',array['Prius'],array['1.8 Hybrid','2.0 Hybrid','Plug-in Hybrid']),
    ('Toyota',array['Yaris'],array['1.0 VVT-i','1.5 VVT-i','1.5 Hybrid']),
    ('Toyota',array['Corolla'],array['1.2 Turbo','1.8 Hybrid','2.0 Hybrid']),
    ('Toyota',array['Corolla Touring Sports','Corolla Cross'],array['1.2 Turbo','1.8 Hybrid','2.0 Hybrid']),
    ('Toyota',array['Auris','Auris Touring Sports'],array['1.33 Dual VVT-i','1.6 Valvematic','1.4 D-4D','1.8 Hybrid']),
    ('Toyota',array['Avensis','Avensis Touring Sports'],array['1.6 Valvematic','1.8 Valvematic','2.0 D-4D','2.2 D-4D']),
    ('Toyota',array['Aygo'],array['1.0 VVT-i']),
    ('Toyota',array['Aygo X'],array['1.0 VVT-i','1.5 Hybrid']),
    ('Toyota',array['iQ'],array['1.0 VVT-i','1.33 Dual VVT-i']),
    ('Toyota',array['Verso'],array['1.6 Valvematic','1.8 Valvematic','2.0 D-4D']),
    ('Toyota',array['Verso-S'],array['1.33 Dual VVT-i']),
    ('Toyota',array['Urban Cruiser'],array['1.33 Dual VVT-i','49 kWh','61 kWh']),
    ('Toyota',array['Yaris Cross'],array['1.5 Hybrid','1.5 Hybrid AWD-i']),
    ('Toyota',array['Yaris GRMN'],array['1.8 Supercharged']),
    ('Toyota',array['GR Yaris'],array['1.6 Turbo']),
    ('Toyota',array['GR Supra'],array['2.0 Turbo','3.0 Turbo']),
    ('Toyota',array['GR86','GT86'],array['2.0 Boxer','2.4 Boxer']),
    ('Toyota',array['C-HR'],array['1.2 Turbo','1.8 Hybrid','2.0 Hybrid','2.0 Plug-in Hybrid']),
    ('Toyota',array['Camry'],array['2.5 Hybrid']),
    ('Toyota',array['Prius Plus'],array['1.8 Hybrid']),
    ('Toyota',array['Mirai'],array['Fuel Cell']),
    ('Toyota',array['bZ4X','bZ4X Touring'],array['57.7 kWh','71.4 kWh','71.4 kWh AWD']),
    ('Toyota',array['Highlander'],array['2.5 Hybrid','3.5 V6']),
    ('Toyota',array['Land Cruiser','Land Cruiser Prado'],array['2.8 D-4D','3.0 D-4D','4.5 V8 D-4D']),
    ('Toyota',array['Hilux'],array['2.4 D-4D','2.8 D-4D','4.0 V6']),
    ('Toyota',array['Hiace'],array['2.5 D-4D','2.8 D-4D']),
    ('Toyota',array['Proace','Proace Verso'],array['1.5 D-4D','2.0 D-4D','50 kWh','75 kWh']),
    ('Toyota',array['Proace City','Proace City Verso'],array['1.2 Turbo','1.5 D-4D','50 kWh']),
    ('Toyota',array['Proace Max'],array['2.2 D-4D','110 kWh']),
    ('Toyota',array['Succeed'],array['1.5 VVT-i']),
    ('Vauxhall',array['Astra'],array['1.2 Turbo','1.4 Turbo','1.6 Turbo','1.5 Diesel','1.6 CDTI','1.7 CDTI']),
    ('Vauxhall',array['Corsa'],array['1.2','1.2 Turbo','1.4','1.4 Turbo','1.3 CDTI','1.5 Diesel']),
    ('Vauxhall',array['Insignia'],array['1.5 Turbo','1.6 CDTI','2.0 CDTI','2.0 Turbo 4x4','2.0 CDTI 4x4']),
    ('Vauxhall',array['Zafira'],array['1.4 Turbo','1.6 CDTI','1.8','2.0 CDTI']),
    ('Volkswagen',array['Golf','Golf Variant'],array['1.0 TSI','1.2 TSI','1.4 TSI','1.5 TSI','1.5 eTSI','1.6 TDI','2.0 TDI','2.0 TDI 4MOTION']),
    ('Volkswagen',array['Golf GTI'],array['2.0 TSI','Clubsport','TCR']),
    ('Volkswagen',array['Golf R','Golf R Variant'],array['2.0 TSI 4MOTION']),
    ('Volkswagen',array['Golf GTD','Golf GTD Variant'],array['2.0 TDI']),
    ('Volkswagen',array['Golf GTE'],array['1.4 eHybrid','1.5 eHybrid']),
    ('Volkswagen',array['Polo'],array['1.0 MPI','1.0 TSI','1.2 TSI','1.4 TDI','1.6 TDI']),
    ('Volkswagen',array['Polo GTI'],array['1.8 TSI','2.0 TSI']),
    ('Volkswagen',array['Passat','Passat Variant'],array['1.4 TSI','1.5 TSI','1.5 eTSI','2.0 TDI','2.0 TDI 4MOTION','2.0 TSI 4MOTION']),
    ('Volkswagen',array['Tiguan','Tiguan Allspace'],array['1.4 TSI','1.5 TSI','2.0 TDI','2.0 TDI 4MOTION','2.0 TSI 4MOTION']),
    ('Volkswagen',array['T-Roc','T-Cross','Taigo'],array['1.0 TSI','1.5 TSI','2.0 TDI','2.0 TSI 4MOTION']),
    ('Volkswagen',array['Touareg'],array['3.0 TDI 4MOTION','3.0 TSI 4MOTION','3.0 eHybrid 4MOTION','4.0 TDI 4MOTION']),
    ('Volkswagen',array['Touran','Sharan'],array['1.2 TSI','1.4 TSI','1.5 TSI','1.6 TDI','2.0 TDI']),
    ('Volkswagen',array['Up!'],array['1.0 MPI','1.0 TSI','GTI']),
    ('Volkswagen',array['Arteon','Arteon Shooting Brake'],array['1.5 TSI','2.0 TDI','2.0 TDI 4MOTION','2.0 TSI 4MOTION','1.4 eHybrid']),
    ('Volkswagen',array['ID.3','ID.4','ID.5','ID.7'],array['Pure','Pro','Pro S','Pro 4MOTION']),
    ('Volkswagen',array['Amarok'],array['2.0 TDI','3.0 TDI 4MOTION','3.0 V6 TDI']),
    ('Volkswagen',array['Arteon R','Arteon R Shooting Brake','Tiguan R','T-Roc R'],array['2.0 TSI 4MOTION']),
    ('Volkswagen',array['Touareg R'],array['3.0 eHybrid 4MOTION']),
    ('Volkswagen',array['Scirocco'],array['1.4 TSI','2.0 TSI','2.0 TDI']),
    ('Volkswagen',array['Scirocco R'],array['2.0 TSI'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

with g(make, models, variants) as (values
    ('Volkswagen',array['Polo R WRC'],array['2.0 TSI']),
    ('Volkswagen',array['Polo Sedan'],array['1.4','1.6']),
    ('Volkswagen',array['Golf Cabriolet'],array['1.2 TSI','1.4 TSI','1.6 TDI','2.0 TDI']),
    ('Volkswagen',array['Golf GTI Cabriolet'],array['2.0 TSI']),
    ('Volkswagen',array['Golf R Cabriolet'],array['2.0 TSI 4MOTION']),
    ('Volkswagen',array['Golf Alltrack'],array['1.8 TSI 4MOTION','2.0 TDI 4MOTION']),
    ('Volkswagen',array['Golf Plus'],array['1.4 TSI','1.6 TDI','2.0 TDI']),
    ('Volkswagen',array['Golf Sportsvan'],array['1.0 TSI','1.4 TSI','1.6 TDI','2.0 TDI']),
    ('Volkswagen',array['Passat Alltrack'],array['2.0 TDI 4MOTION','2.0 TSI 4MOTION']),
    ('Volkswagen',array['Passat GTE'],array['1.4 eHybrid','1.5 eHybrid']),
    ('Volkswagen',array['CC'],array['1.8 TSI','2.0 TSI','2.0 TDI','3.6 V6 4MOTION']),
    ('Volkswagen',array['Eos'],array['1.4 TSI','2.0 TSI','2.0 TDI','3.2 V6']),
    ('Volkswagen',array['Jetta'],array['1.2 TSI','1.4 TSI','1.6 TDI','2.0 TDI']),
    ('Volkswagen',array['Fox'],array['1.2','1.4']),
    ('Volkswagen',array['The Beetle','The Beetle Cabriolet'],array['1.2 TSI','1.4 TSI','2.0 TSI','1.6 TDI','2.0 TDI']),
    ('Volkswagen',array['Phaeton'],array['3.0 V6 TDI','4.2 V8','6.0 W12']),
    ('Volkswagen',array['Tharu'],array['1.4 TSI','1.5 TSI']),
    ('Volkswagen',array['Tayron'],array['1.5 eTSI','2.0 TDI 4MOTION','1.5 eHybrid','2.0 TSI 4MOTION']),
    ('Volkswagen',array['T-Roc Cabriolet'],array['1.0 TSI','1.5 TSI']),
    ('Volkswagen',array['XL1'],array['0.8 TDI Hybrid']),
    ('Volkswagen',array['Caddy','Caddy Cargo','Caddy California'],array['1.5 TSI','2.0 TDI','2.0 TDI 4MOTION']),
    ('Volkswagen',array['Transporter','Caravelle','Multivan','T5 Multivan','T6 Multivan','T7 Multivan'],array['2.0 TDI','2.0 TDI 4MOTION','2.0 TSI','1.4 eHybrid']),
    ('Volkswagen',array['California','Grand California'],array['2.0 TDI','2.0 TDI 4MOTION']),
    ('Volkswagen',array['Crafter'],array['2.0 TDI','2.0 TDI 4MOTION']),
    ('Volkswagen',array['e-Crafter'],array['35.8 kWh']),
    ('Volkswagen',array['e-Transporter','e-Caravelle'],array['32.3 kWh']),
    ('Volkswagen',array['e-Golf'],array['24.2 kWh','35.8 kWh']),
    ('Volkswagen',array['e-up!'],array['18.7 kWh','32.3 kWh']),
    ('Volkswagen',array['ID. Polo'],array['38 kWh','56 kWh']),
    ('Volkswagen',array['ID. Buzz','ID. Buzz Cargo'],array['77 kWh','79 kWh','86 kWh']),
    ('Volkswagen',array['ID. Buzz GTX'],array['86 kWh GTX 4MOTION']),
    ('Volkswagen',array['ID.3 GTX','ID.4 GTX','ID.5 GTX','ID.7 GTX','ID.7 GTX Tourer'],array['GTX','GTX Performance']),
    ('Volkswagen',array['ID.7 Tourer'],array['Pro','Pro S'])
)
insert into public.variants (model_id, name, source)
select mo.id, v.name, 'catalog_variants_v1'
from g
cross join lateral unnest(g.variants) as v(name)
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(g.make)
join public.models mo on mo.make_id = mk.id and exists (
  select 1 from unnest(g.models) m
  where public.normalize_vehicle_name(m) = mo.normalized_name)
on conflict (model_id, normalized_name) do nothing;

-- ---------- remap: rows seeded as models that are really trims ----------
create temp table _remap on commit drop as
select * from (values
    ('Audi','A3 allstreet TFSI e','A3 allstreet','40 TFSI e'),
    ('Audi','A3 Sportback TFSI e','A3 Sportback','40 TFSI e'),
    ('Audi','A5 Avant e-hybrid','A5 Avant','e-hybrid 299 PS'),
    ('Audi','A5 Limousine e-hybrid','A5 Limousine','e-hybrid 299 PS'),
    ('Audi','A6 Avant e-hybrid','A6 Avant','e-hybrid 299 PS'),
    ('Audi','A6 Limousine e-hybrid','A6 Limousine','e-hybrid 299 PS'),
    ('Audi','Q3 e-hybrid','Q3','45 TFSI e'),
    ('Audi','Q3 Sportback e-hybrid','Q3 Sportback','45 TFSI e'),
    ('Audi','Q5 e-hybrid','Q5','e-hybrid 299 PS'),
    ('Audi','Q5 Sportback e-hybrid','Q5 Sportback','e-hybrid 299 PS'),
    ('BMW','114d','1 Series','114d'),
    ('BMW','114i','1 Series','114i'),
    ('BMW','116','1 Series','116'),
    ('BMW','116d','1 Series','116d'),
    ('BMW','116i','1 Series','116i'),
    ('BMW','118d','1 Series','118d'),
    ('BMW','118i','1 Series','118i'),
    ('BMW','120','1 Series','120'),
    ('BMW','120d','1 Series','120d'),
    ('BMW','120i','1 Series','120i'),
    ('BMW','123d','1 Series','123d'),
    ('BMW','125d','1 Series','125d'),
    ('BMW','125i','1 Series','125i'),
    ('BMW','128ti','1 Series','128ti'),
    ('BMW','135i','1 Series','135i'),
    ('BMW','M135','1 Series','M135'),
    ('BMW','M135i','1 Series','M135i'),
    ('BMW','M140i','1 Series','M140i'),
    ('BMW','214d','2 Series Active Tourer','214d'),
    ('BMW','216d','2 Series Active Tourer','216d'),
    ('BMW','216i','2 Series Active Tourer','216i'),
    ('BMW','218d','2 Series Coupé','218d'),
    ('BMW','218i','2 Series Coupé','218i'),
    ('BMW','220','2 Series Coupé','220'),
    ('BMW','220d','2 Series Coupé','220d'),
    ('BMW','220i','2 Series Coupé','220i'),
    ('BMW','220i Active Tourer','2 Series Active Tourer','220i'),
    ('BMW','223d','2 Series Active Tourer','223d'),
    ('BMW','223i','2 Series Active Tourer','223i'),
    ('BMW','225d','2 Series Coupé','225d'),
    ('BMW','225e','2 Series Active Tourer','225e'),
    ('BMW','225i','2 Series Active Tourer','225i'),
    ('BMW','225xe','2 Series Active Tourer','225xe'),
    ('BMW','228i','2 Series Coupé','228i'),
    ('BMW','230e','2 Series Active Tourer','230e'),
    ('BMW','230i','2 Series Coupé','230i'),
    ('BMW','M235','2 Series Coupé','M235'),
    ('BMW','M235i','2 Series Coupé','M235i'),
    ('BMW','M240i','2 Series Coupé','M240i'),
    ('BMW','316d','3 Series','316d'),
    ('BMW','316i','3 Series','316i'),
    ('BMW','318d','3 Series','318d'),
    ('BMW','318i','3 Series','318i'),
    ('BMW','320d','3 Series','320d'),
    ('BMW','320e','3 Series','320e'),
    ('BMW','320i','3 Series','320i'),
    ('BMW','325d','3 Series','325d'),
    ('BMW','325i','3 Series','325i'),
    ('BMW','328i','3 Series','328i'),
    ('BMW','330d','3 Series','330d'),
    ('BMW','330e','3 Series','330e'),
    ('BMW','330i','3 Series','330i'),
    ('BMW','335d','3 Series','335d'),
    ('BMW','335i','3 Series','335i'),
    ('BMW','340i','3 Series','340i'),
    ('BMW','M340d','3 Series','M340d'),
    ('BMW','M340d xDrive Touring','3 Series Touring','M340d'),
    ('BMW','M340i','3 Series','M340i'),
    ('BMW','418d','4 Series Coupé','418d'),
    ('BMW','418i','4 Series Coupé','418i'),
    ('BMW','420d','4 Series Coupé','420d'),
    ('BMW','420i','4 Series Coupé','420i'),
    ('BMW','425d','4 Series Coupé','425d'),
    ('BMW','428i','4 Series Coupé','428i'),
    ('BMW','430d','4 Series Coupé','430d'),
    ('BMW','430i','4 Series Coupé','430i'),
    ('BMW','435d','4 Series Coupé','435d'),
    ('BMW','435i','4 Series Coupé','435i'),
    ('BMW','440i','4 Series Coupé','440i'),
    ('BMW','M440d','4 Series Coupé','M440d'),
    ('BMW','M440i','4 Series Coupé','M440i'),
    ('BMW','518d','5 Series','518d'),
    ('BMW','520d','5 Series','520d'),
    ('BMW','520e','5 Series','520e'),
    ('BMW','520i','5 Series','520i'),
    ('BMW','523i','5 Series','523i'),
    ('BMW','525d','5 Series','525d'),
    ('BMW','528i','5 Series','528i'),
    ('BMW','530d','5 Series','530d'),
    ('BMW','530e','5 Series','530e'),
    ('BMW','530i','5 Series','530i'),
    ('BMW','535d','5 Series','535d'),
    ('BMW','535i','5 Series','535i'),
    ('BMW','540d','5 Series','540d'),
    ('BMW','540i','5 Series','540i'),
    ('BMW','545e','5 Series','545e'),
    ('BMW','550e','5 Series','550e'),
    ('BMW','550i','5 Series','550i'),
    ('BMW','M550d','5 Series','M550d'),
    ('BMW','M550i','5 Series','M550i'),
    ('BMW','620d','6 Series Gran Turismo','620d'),
    ('BMW','630d','6 Series Gran Turismo','630d'),
    ('BMW','630i','6 Series Gran Turismo','630i'),
    ('BMW','640d','6 Series Coupé','640d'),
    ('BMW','640i','6 Series Coupé','640i'),
    ('BMW','650i','6 Series Coupé','650i'),
    ('BMW','730d','7 Series','730d'),
    ('BMW','740d','7 Series','740d'),
    ('BMW','740e','7 Series','740e'),
    ('BMW','740i','7 Series','740i'),
    ('BMW','745e','7 Series','745e'),
    ('BMW','750d','7 Series','750d'),
    ('BMW','750i','7 Series','750i'),
    ('BMW','760i','7 Series','760i'),
    ('BMW','M760e','7 Series','M760e'),
    ('BMW','M760i','7 Series','M760i'),
    ('BMW','840d','8 Series Coupé','840d'),
    ('BMW','840i','8 Series Coupé','840i'),
    ('BMW','850i','8 Series Coupé','850i'),
    ('BMW','M850i','8 Series Coupé','M850i'),
    ('BMW','20 xDrive','X1','xDrive20d'),
    ('BMW','sDrive16d','X1','sDrive16d'),
    ('BMW','sDrive18d','X1','sDrive18d'),
    ('BMW','sDrive18i','X1','sDrive18i'),
    ('BMW','sDrive20d','X1','sDrive20d'),
    ('BMW','sDrive20i','X1','sDrive20i'),
    ('BMW','sDrive25d','X2','sDrive25d'),
    ('BMW','sDrive23i','Z4','sDrive23i'),
    ('BMW','sDrive28i','Z4','sDrive28i'),
    ('BMW','sDrive30i','Z4','sDrive30i'),
    ('BMW','sDrive35i','Z4','sDrive35i'),
    ('BMW','M35i','X1','M35i'),
    ('BMW','xDrive18d','X1','xDrive18d'),
    ('BMW','xDrive23i','X1','xDrive23i'),
    ('BMW','xDrive25e','X1','xDrive25e'),
    ('BMW','xDrive20d','X3','xDrive20d'),
    ('BMW','xDrive20i','X3','xDrive20i'),
    ('BMW','xDrive23d','X3','xDrive23d'),
    ('BMW','xDrive25d','X3','xDrive25d'),
    ('BMW','xDrive28i','X3','xDrive28i'),
    ('BMW','xDrive30e','X3','xDrive30e'),
    ('BMW','xDrive30i','X3','xDrive30i'),
    ('BMW','M40d','X3','M40d'),
    ('BMW','M40i','X3','M40i'),
    ('BMW','xDrive30d','X5','xDrive30d'),
    ('BMW','xDrive35d','X5','xDrive35d'),
    ('BMW','xDrive35i','X5','xDrive35i'),
    ('BMW','xDrive40d','X5','xDrive40d'),
    ('BMW','xDrive40e','X5','xDrive40e'),
    ('BMW','xDrive40i','X5','xDrive40i'),
    ('BMW','xDrive45e','X5','xDrive45e'),
    ('BMW','xDrive50e','X5','xDrive50e'),
    ('BMW','xDrive50i','X5','xDrive50i'),
    ('BMW','M50d','X5','M50d'),
    ('BMW','M50i','X5','M50i'),
    ('BMW','M60i','X5','M60i'),
    ('BMW','M50','i4','M50'),
    ('Mercedes','A 160','A-Class','A 160'),
    ('Mercedes','A 180','A-Class','A 180'),
    ('Mercedes','A 200','A-Class','A 200'),
    ('Mercedes','A 220','A-Class','A 220'),
    ('Mercedes','A 250','A-Class','A 250'),
    ('Mercedes','A 250 e','A-Class','A 250 e'),
    ('Mercedes','B 160','B-Class','B 160'),
    ('Mercedes','B 180','B-Class','B 180'),
    ('Mercedes','B 200','B-Class','B 200'),
    ('Mercedes','B 220','B-Class','B 220'),
    ('Mercedes','B 250','B-Class','B 250'),
    ('Mercedes','B 250 e','B-Class','B 250 e'),
    ('Mercedes','C 160','C-Class','C 160'),
    ('Mercedes','C 180','C-Class','C 180'),
    ('Mercedes','C 200','C-Class','C 200'),
    ('Mercedes','C 220 d','C-Class','C 220 d'),
    ('Mercedes','C 250','C-Class','C 250'),
    ('Mercedes','C 300','C-Class','C 300'),
    ('Mercedes','C 300 de','C-Class','C 300 de'),
    ('Mercedes','C 300 e','C-Class','C 300 e'),
    ('Mercedes','C 350','C-Class','C 350'),
    ('Mercedes','C 350 e','C-Class','C 350 e'),
    ('Mercedes','C 400','C-Class','C 400'),
    ('Mercedes','CLA 180','CLA','CLA 180'),
    ('Mercedes','CLA 200','CLA','CLA 200'),
    ('Mercedes','CLA 220','CLA','CLA 220'),
    ('Mercedes','CLA 250','CLA','CLA 250'),
    ('Mercedes','CLA 250 e','CLA','CLA 250 e'),
    ('Mercedes','CLA 350','CLA','CLA 350'),
    ('Mercedes','CLE 180','CLE','CLE 180'),
    ('Mercedes','CLE 200','CLE','CLE 200'),
    ('Mercedes','CLE 200 4MATIC','CLE','CLE 200 4MATIC'),
    ('Mercedes','CLE 220 d','CLE','CLE 220 d'),
    ('Mercedes','CLE 300','CLE','CLE 300'),
    ('Mercedes','CLE 300 4MATIC','CLE','CLE 300 4MATIC'),
    ('Mercedes','CLE 300 e (Plug-in Hybrid)','CLE','CLE 300 e'),
    ('Mercedes','CLE 450 4MATIC','CLE','CLE 450 4MATIC'),
    ('Mercedes','CLS 250 d','CLS','CLS 250 d'),
    ('Mercedes','CLS 300 d','CLS','CLS 300 d'),
    ('Mercedes','CLS 350','CLS','CLS 350'),
    ('Mercedes','CLS 400','CLS','CLS 400'),
    ('Mercedes','CLS 450','CLS','CLS 450'),
    ('Mercedes','CLS 500','CLS','CLS 500'),
    ('Mercedes','E 200','E-Class','E 200'),
    ('Mercedes','E 220 d','E-Class','E 220 d'),
    ('Mercedes','E 250','E-Class','E 250'),
    ('Mercedes','E 300','E-Class','E 300'),
    ('Mercedes','E 300 de','E-Class','E 300 de'),
    ('Mercedes','E 300 e','E-Class','E 300 e'),
    ('Mercedes','E 350','E-Class','E 350'),
    ('Mercedes','E 350 e','E-Class','E 350 e'),
    ('Mercedes','E 400','E-Class','E 400'),
    ('Mercedes','E 450','E-Class','E 450'),
    ('Mercedes','E 500','E-Class','E 500'),
    ('Mercedes','G 350 d','G-Class','G 350 d'),
    ('Mercedes','G 400 d','G-Class','G 400 d'),
    ('Mercedes','G 450 d','G-Class','G 450 d'),
    ('Mercedes','G 500','G-Class','G 500'),
    ('Mercedes','G 580','G-Class','G 580 mit EQ Technologie'),
    ('Mercedes','GLA 160','GLA','GLA 160'),
    ('Mercedes','GLA 180','GLA','GLA 180'),
    ('Mercedes','GLA 200','GLA','GLA 200'),
    ('Mercedes','GLA 220','GLA','GLA 220'),
    ('Mercedes','GLA 250','GLA','GLA 250'),
    ('Mercedes','GLA 250 e','GLA','GLA 250 e'),
    ('Mercedes','GLB 180','GLB','GLB 180'),
    ('Mercedes','GLB 200','GLB','GLB 200'),
    ('Mercedes','GLB 220','GLB','GLB 220'),
    ('Mercedes','GLB 250','GLB','GLB 250'),
    ('Mercedes','GLC 200','GLC','GLC 200'),
    ('Mercedes','GLC 220 d','GLC','GLC 220 d'),
    ('Mercedes','GLC 250','GLC','GLC 250'),
    ('Mercedes','GLC 300','GLC','GLC 300'),
    ('Mercedes','GLC 300 de','GLC','GLC 300 de'),
    ('Mercedes','GLC 300 e','GLC','GLC 300 e'),
    ('Mercedes','GLC 350 e','GLC','GLC 350 e'),
    ('Mercedes','GLC 400 d','GLC','GLC 400 d'),
    ('Mercedes','GLC 400 e','GLC','GLC 400 e'),
    ('Mercedes','GLE 250 d','GLE','GLE 250 d'),
    ('Mercedes','GLE 300 d','GLE','GLE 300 d'),
    ('Mercedes','GLE 350','GLE','GLE 350'),
    ('Mercedes','GLE 350 de','GLE','GLE 350 de'),
    ('Mercedes','GLE 400','GLE','GLE 400'),
    ('Mercedes','GLE 400 e','GLE','GLE 400 e'),
    ('Mercedes','GLE 450','GLE','GLE 450'),
    ('Mercedes','GLE 500','GLE','GLE 500'),
    ('Mercedes','GLE 500 e','GLE','GLE 500 e'),
    ('Mercedes','GLS 350 d','GLS','GLS 350 d'),
    ('Mercedes','GLS 400','GLS','GLS 400'),
    ('Mercedes','GLS 450','GLS','GLS 450'),
    ('Mercedes','GLS 500','GLS','GLS 500'),
    ('Mercedes','GLS 580','GLS','GLS 580'),
    ('Mercedes','S 350 d','S-Class','S 350 d'),
    ('Mercedes','S 400','S-Class','S 400'),
    ('Mercedes','S 450','S-Class','S 450'),
    ('Mercedes','S 500','S-Class','S 500'),
    ('Mercedes','S 500 e','S-Class','S 500 e'),
    ('Mercedes','S 560','S-Class','S 560'),
    ('Mercedes','S 560 e','S-Class','S 560 e'),
    ('Mercedes','S 580','S-Class','S 580'),
    ('Mercedes','S 580 e','S-Class','S 580 e'),
    ('Mercedes','S 600','S-Class','S 600'),
    ('Mercedes','SL 350','SL','SL 350'),
    ('Mercedes','SL 400','SL','SL 400'),
    ('Mercedes','SL 500','SL','SL 500'),
    ('Mercedes','SLC 180','SLC','SLC 180'),
    ('Mercedes','SLC 200','SLC','SLC 200'),
    ('Mercedes','SLC 250 d','SLC','SLC 250 d'),
    ('Mercedes','SLC 300','SLC','SLC 300'),
    ('Mercedes','V 200','V-Class','V 200'),
    ('Mercedes','V 220 d','V-Class','V 220 d'),
    ('Mercedes','V 250 d','V-Class','V 250 d'),
    ('Mercedes','V 300 d','V-Class','V 300 d'),
    ('Mercedes','Maybach S 560','Maybach S-Class','S 560 4MATIC'),
    ('Mercedes','Maybach S 580','Maybach S-Class','S 580 4MATIC'),
    ('Mercedes','Maybach S 600','Maybach S-Class','S 600'),
    ('Mercedes','Maybach S 650','Maybach S-Class','S 650'),
    ('Mercedes','Maybach S 680','Maybach S-Class','S 680 4MATIC'),
    ('Mercedes','AMG CLE 53 4MATIC+','AMG CLE 53','CLE 53 4MATIC+'),
    ('Mercedes','Mercedes-AMG GT 63 4MATIC+','AMG GT','GT 63 4MATIC+'),
    ('Mini','One','Hatch','One'),
    ('Mini','Cooper','Hatch','Cooper'),
    ('Mini','Cooper S','Hatch','Cooper S'),
    ('Mini','John Cooper Works','Hatch','John Cooper Works'),
    ('Mini','Cooper Electric','Hatch','Cooper E'),
    ('Mini','John Cooper Works Electric','Hatch','John Cooper Works Electric'),
    ('Mini','Cooper 5-Türer','Hatch 5-Türer','Cooper'),
    ('Mini','Cooper S 5-Türer','Hatch 5-Türer','Cooper S'),
    ('Mini','Cabrio Cooper S','Cabrio','Cooper S'),
    ('Mini','Cabrio John Cooper Works','Cabrio','John Cooper Works'),
    ('Mini','Clubman Cooper S','Clubman','Cooper S'),
    ('Mini','Clubman John Cooper Works','Clubman','John Cooper Works'),
    ('Mini','Countryman Cooper S','Countryman','Cooper S'),
    ('Mini','Countryman John Cooper Works','Countryman','John Cooper Works'),
    ('Mini','Countryman Electric','Countryman','Countryman E'),
    ('Mini','Coupé Cooper S','Coupé','Cooper S'),
    ('Mini','Coupé John Cooper Works','Coupé','John Cooper Works'),
    ('Mini','Paceman Cooper S','Paceman','Cooper S'),
    ('Mini','Paceman John Cooper Works','Paceman','John Cooper Works'),
    ('Mini','Roadster Cooper S','Roadster','Cooper S'),
    ('Mini','Roadster John Cooper Works','Roadster','John Cooper Works'),
    ('Mini','Aceman John Cooper Works','Aceman','John Cooper Works'),
    ('Opel','Astra H OPC','Astra','OPC'),
    ('Opel','Astra J OPC','Astra','OPC'),
    ('Opel','Corsa D OPC','Corsa','OPC'),
    ('Opel','Corsa E OPC','Corsa','OPC'),
    ('Opel','Insignia A OPC','Insignia','OPC'),
    ('Opel','Zafira B OPC','Zafira','OPC'),
    ('Porsche','911 Carrera','911','Carrera'),
    ('Porsche','911 Carrera 4','911','Carrera 4'),
    ('Porsche','911 Carrera 4S','911','Carrera 4S'),
    ('Porsche','911 Carrera S','911','Carrera S'),
    ('Porsche','911 Carrera T','911','Carrera T'),
    ('Porsche','911 GTS','911','Carrera GTS'),
    ('Porsche','911 Targa','911','Targa 4'),
    ('Porsche','911 Turbo','911','Turbo'),
    ('Porsche','911 Turbo S','911','Turbo S'),
    ('Porsche','718 Boxster GTS','718 Boxster','GTS 4.0'),
    ('Porsche','718 Boxster S','718 Boxster','S'),
    ('Porsche','718 Boxster T','718 Boxster','T'),
    ('Porsche','718 Cayman GTS','718 Cayman','GTS 4.0'),
    ('Porsche','718 Cayman S','718 Cayman','S'),
    ('Porsche','718 Cayman T','718 Cayman','T'),
    ('Porsche','Cayenne E-Hybrid','Cayenne','E-Hybrid'),
    ('Porsche','Cayenne GTS','Cayenne','GTS'),
    ('Porsche','Cayenne S','Cayenne','S'),
    ('Porsche','Cayenne S E-Hybrid','Cayenne','S E-Hybrid'),
    ('Porsche','Cayenne Turbo','Cayenne','Turbo'),
    ('Porsche','Cayenne Turbo E-Hybrid','Cayenne','Turbo E-Hybrid'),
    ('Porsche','Cayenne Turbo GT','Cayenne','Turbo GT'),
    ('Porsche','Cayenne Turbo S E-Hybrid','Cayenne','Turbo S E-Hybrid'),
    ('Porsche','Cayenne Turbo Electric','Cayenne Electric','Turbo Electric'),
    ('Porsche','Macan 4','Macan','Macan 4'),
    ('Porsche','Macan 4S','Macan','Macan 4S'),
    ('Porsche','Macan GTS','Macan','GTS'),
    ('Porsche','Macan S','Macan','S'),
    ('Porsche','Macan T','Macan','T'),
    ('Porsche','Macan Turbo','Macan','Turbo'),
    ('Porsche','Panamera 4','Panamera','Panamera 4'),
    ('Porsche','Panamera 4 E-Hybrid','Panamera','4 E-Hybrid'),
    ('Porsche','Panamera 4S','Panamera','Panamera 4S'),
    ('Porsche','Panamera 4S E-Hybrid','Panamera','4S E-Hybrid'),
    ('Porsche','Panamera GTS','Panamera','GTS'),
    ('Porsche','Panamera S','Panamera','S'),
    ('Porsche','Panamera S E-Hybrid','Panamera','S E-Hybrid'),
    ('Porsche','Panamera Turbo','Panamera','Turbo'),
    ('Porsche','Panamera Turbo E-Hybrid','Panamera','Turbo E-Hybrid'),
    ('Porsche','Panamera Turbo S','Panamera','Turbo S'),
    ('Porsche','Panamera Turbo S E-Hybrid','Panamera','Turbo S E-Hybrid'),
    ('Porsche','Taycan 4S','Taycan','Taycan 4S'),
    ('Porsche','Taycan GTS','Taycan','GTS'),
    ('Porsche','Taycan Turbo','Taycan','Turbo'),
    ('Porsche','Taycan Turbo GT','Taycan','Turbo GT'),
    ('Porsche','Taycan Turbo S','Taycan','Turbo S'),
    ('Renault','Clio RS Trophy','Clio RS','Trophy'),
    ('Renault','Megane RS Trophy','Megane RS','Trophy'),
    ('Renault','Megane RS Trophy-R','Megane RS','Trophy-R'),
    ('Renault','Clio GT','Clio','GT'),
    ('Renault','Twingo GT','Twingo','GT'),
    ('Toyota','Prius Plug-In Hybrid','Prius','Plug-in Hybrid'),
    ('Vauxhall','Astra H VXR','Astra','VXR'),
    ('Vauxhall','Astra J VXR','Astra','VXR'),
    ('Vauxhall','Corsa D VXR','Corsa','VXR'),
    ('Vauxhall','Corsa E VXR','Corsa','VXR'),
    ('Vauxhall','Insignia A VXR','Insignia','VXR'),
    ('Vauxhall','Zafira B VXR','Zafira','VXR'),
    ('Volkswagen','Golf GTI Clubsport','Golf GTI','Clubsport'),
    ('Volkswagen','Golf GTI TCR','Golf GTI','TCR'),
    ('Volkswagen','up! GTI','Up!','GTI')
) as t(make, from_name, model, variant);

insert into public.variants (model_id, name, source)
select mo.id, r.variant, 'catalog_variants_v1'
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(r.model)
on conflict (model_id, normalized_name) do nothing;

insert into public.vehicle_aliases (entity_type, make_id, model_id, alias, normalized_alias, source)
select 'model', mk.id, mo.id, r.from_name, public.normalize_vehicle_name(r.from_name), 'catalog_variants_v1'
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(r.model)
where not exists (
  select 1 from public.vehicle_aliases va
  where va.entity_type = 'model' and va.make_id = mk.id
    and va.normalized_alias = public.normalize_vehicle_name(r.from_name));

update public.listings l
set model_id = mo.id, variant_id = v.id
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
join public.models orphan on orphan.make_id = mk.id
 and orphan.normalized_name = public.normalize_vehicle_name(r.from_name)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(r.model)
join public.variants v on v.model_id = mo.id
 and v.normalized_name = public.normalize_vehicle_name(r.variant)
where l.model_id = orphan.id;

update public.models mo set is_active = false, updated_at = now()
from _remap r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
where mo.make_id = mk.id
  and mo.normalized_name = public.normalize_vehicle_name(r.from_name);

-- ---------- rename: generation codes and inconsistent spellings ----------
create temp table _rename on commit drop as
select * from (values
    ('Hyundai','IONIQ 5 N','Ioniq 5 N'),
    ('Hyundai','IONIQ 6 N','Ioniq 6 N'),
    ('Renault','Megane RS','Mégane RS')
) as t(make, from_name, to_name);

insert into public.vehicle_aliases (entity_type, make_id, model_id, alias, normalized_alias, source)
select 'model', mk.id, mo.id, r.from_name, public.normalize_vehicle_name(r.from_name), 'catalog_variants_v1'
from _rename r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(r.from_name)
where not exists (
  select 1 from public.vehicle_aliases va
  where va.entity_type = 'model' and va.make_id = mk.id
    and va.normalized_alias = public.normalize_vehicle_name(r.from_name));

update public.models mo set name = r.to_name, updated_at = now()
from _rename r
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(r.make)
where mo.make_id = mk.id
  and mo.normalized_name = public.normalize_vehicle_name(r.from_name)
  and not exists (
    select 1 from public.models other
    where other.make_id = mk.id
      and other.id <> mo.id
      and other.normalized_name = public.normalize_vehicle_name(r.to_name));

-- ---------- merge: duplicate, generation and equipment-line rows ----------
create temp table _merge on commit drop as
select * from (values
    ('Audi','Q6 SUV e-tron','Q6 e-tron'),
    ('Opel','Zafira B','Zafira'),
    ('Opel','Zafira Tourer C','Zafira Tourer'),
    ('Volkswagen','Passat R-Line','Passat'),
    ('Volkswagen','Tiguan R-Line','Tiguan'),
    ('Volkswagen','T-Roc R-Line','T-Roc'),
    ('Volkswagen','Passat V facelift','Passat'),
    ('Volkswagen','Touran I facelift','Touran')
) as t(make, from_name, model);

insert into public.vehicle_aliases (entity_type, make_id, model_id, alias, normalized_alias, source)
select 'model', mk.id, mo.id, m.from_name, public.normalize_vehicle_name(m.from_name), 'catalog_variants_v1'
from _merge m
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(m.make)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(m.model)
where not exists (
  select 1 from public.vehicle_aliases va
  where va.entity_type = 'model' and va.make_id = mk.id
    and va.normalized_alias = public.normalize_vehicle_name(m.from_name));

update public.listings l
set model_id = mo.id
from _merge m
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(m.make)
join public.models orphan on orphan.make_id = mk.id
 and orphan.normalized_name = public.normalize_vehicle_name(m.from_name)
join public.models mo on mo.make_id = mk.id
 and mo.normalized_name = public.normalize_vehicle_name(m.model)
where l.model_id = orphan.id;

update public.models mo set is_active = false, updated_at = now()
from _merge m
join public.makes mk on mk.normalized_name = public.normalize_vehicle_name(m.make)
where mo.make_id = mk.id
  and mo.normalized_name = public.normalize_vehicle_name(m.from_name);

commit;