// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgalkhfopecwsryracre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnYWxraGZvcGVjd3NyeXJhY3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTgyNTcsImV4cCI6MjA3MTUzNDI1N30.NVkJifm16QeDNEE_E2HBjkcVhWHksCN4gCyvjT5T0RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
